### ISSUE TITLE
Uncaught TypeError: headerLink.magnificPopup is not a function

### ISSUE THREAD

**Issue by yousufhanif26** [mageplaza/magento-2-social-login#10]
![js-error](https://cloud.githubusercontent.com/assets/22050335/22690902/b60c5338-ed59-11e6-8167-68c45ca5a4ee.png)
I am getting error when page refresh.
Uncaught TypeError: headerLink.magnificPopup is not a function.(popup.phtml)
Uncaught TypeError: e is not a function (jquery.magnific-popup.min.js)

**Comment by msliman** [comment]
I have also this bug. How to solve it?

**Comment by shivkumarsingh7** [comment]
How to solve this? Without any solution, this issue is closed?
