### ISSUE TITLE
Wrong class applied to message after successful login

### ISSUE THREAD

**Issue by UglyWillDuckling** [mageplaza/magento-2-social-login#100]
### Preconditions

1. Magento: 2.2.4
2. PHP: 7.0
3. MySQL: 

### Steps to reproduce

1. open login popup
2. enter valid credentials

### Expected result

1.  see message with success class

### Actual result

1. message with error class shows

**Comment by MaxxLuong** [comment]
Thanks @UglyWillDuckling,
We have noted and our team will implement this soon.

**Comment by MaxxLuong** [comment]
Hi there,

Thank for your information.
This issue is solved. I'm close ticket now.
