### ISSUE TITLE
Override Mageplaza_Core requirejs-config.js

### ISSUE THREAD

**Issue by mageho** [mageplaza/magento-2-social-login#101]
Good evening,

I would like to know how you can override requirejs-config.js of your module Mageplaza_Core which is declared in base folder.

Indeed, I can not override this file in my custom theme (Mageplaza_Core/requirejs-config.js), I would like to know how I can do that. I did a lot of research, but all I can find was about replacing a core js file and not a requirejs-config one.

Your file load multiple librairies we are not using.

Thank you,

Ilan PARMENTIER

**Comment by MaxxLuong** [comment]
Hi there,
This file is not load any the libraries on your page If you don't call them out to use. You can see this here: http://requirejs.org/docs/api.html

**Comment by mageho** [comment]
Hello,

Indeed, it seems I misterunderstand this component.

I close this issue.

Thank you,

Ilan PARMENTIER
