### ISSUE TITLE
Captcha not working on register page in magento 2.2.3

### ISSUE THREAD

**Issue by santhoshnsscoe** [mageplaza/magento-2-social-login#103]
### Preconditions
1. Magento: 2.2.3
2. PHP: 7.1
3. MySQL: 5.7

### Steps to reproduce
1.  Enable the captcha for registration page
2. Enable social login module

### Expected result
1.  The captcha should work properly.

### Actual result
1. Always getting Incorrect Captcha
2. When we reload the captcha and then try, it is working fine
3. Disabled the social login, the captcha is working fine without any problem.

Checked and got that the captcha is getting called two times and the latest value is hidden in the social login popup. 

Solution might be to get the captcha value loaded in register page and add that value to the social login hidden popup.

**Comment by MaxxLuong** [comment]
Close due to no response in 7 days

**Comment by MaxxLuong** [comment]
Close due to no response in 7 days

**Comment by santhoshnsscoe** [comment]
When "Use Popup Login" is select to "Yes", then the error comes. So, we have now made it as No.

<img width="625" alt="Configuration Use Popup Login" src="https://user-images.githubusercontent.com/4706320/42077096-58e88ed0-7b95-11e8-85f4-e5e30117f31a.png">
