### ISSUE TITLE
Facebook Social Login returns the error "Can't Load URL: The domain of this URL isn't included in the app's domains"

### ISSUE THREAD

**Issue by saeedsweans** [mageplaza/magento-2-social-login#105]
Facebook Social Login returns the error "Can't Load URL: The domain of this URL isn't included in the app's domains"

### Preconditions

1. Magento: 2.2.0

### Steps to reproduce

1. Go to https://myg.in/customer/account/login/
2.  Click on login with facebook icon
![myg settings facebook for developers](https://user-images.githubusercontent.com/38320542/41652413-9285424c-74a0-11e8-8e9e-b82368967988.png)
![myg settings facebook for developers 2](https://user-images.githubusercontent.com/38320542/41652414-92bd2c5c-74a0-11e8-8beb-f065a45cc881.png)

### Expected result

1.  Login with facebook window

### Actual result

1. {
   "error": {
      "message": "Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.",
      "type": "OAuthException",
      "code": 191,
      "fbtrace_id": "AZgmoW9vET9"
   }
}

Our website is https://myg.in/

**Comment by datvm1** [comment]
Hi,

It appears that you are using Magenest_SocialLogin extension. Please contact their support for better help on this matter.

**Comment by MaxxLuong** [comment]
Close due to no response in 7 days

**Comment by l4red0** [comment]
@saeedsweans Had this same issue. In FB app configuration under the "Valid OAuth Redirect URIs", put `https://myg.in/social/account/callback/provider/facebook/`

Unfortunately this is not documented anywhere.

**Comment by datvm1** [comment]
Hi Leszek,
In the case that you use Mageplaza Social Login extension, there is a field in our backend config, Valid OAuth redirect URIs:
![image](https://user-images.githubusercontent.com/35990443/42152082-4c7b39ce-7e09-11e8-9994-952328d66936.png)
that you can copy its value and paste into "Valid OAuth Redirect URIs" inside your Facebook app configuration.
It is different for each site, in my image I had the extension installed on my local.

**Comment by l4red0** [comment]
Tahnks @datvm1 but indeed my solution is for aheadworks social login extension - like in op's case I presume. And there is no field with OAuth Redirect address like in your picture.
