### ISSUE TITLE
Instagram Login issue of Hybrid Auth library

### ISSUE THREAD

**Issue by honeygarg** [mageplaza/magento-2-social-login#106]
1. Magento: 2.2.2
2. PHP: 7.x

### Steps to reproduce
1. Please click on the site: https://fcentral.testingdemo.net/ 
2. And click on SignUp/ SignIn link and using with Instagram
3. Login with credentials as ebiz1361/ Simple@123
4. And the popup display with-
HybridAuth
Open Source Social Sign On PHP Library.
hybridauth.sourceforge.net/

**Comment by MaxxLuong** [comment]
Hi there, 
Could you provide me some screenshot of this issue?

**Comment by honeygarg** [comment]
![instagram_login](https://user-images.githubusercontent.com/20253827/41709002-bbbdd592-755f-11e8-8134-de92c7a54f32.png)

**Comment by MaxxLuong** [comment]
I don't see this error on my local machine. I think that this just happened on your site. Please create a ticket here: [mageplaza.com/contact.html](https://www.mageplaza.com/contact.html). Our team will help you check this issue.

**Comment by honeygarg** [comment]
The problem occurring is started a few days ago. Before it was working perfect

**Comment by MaxxLuong** [comment]
This issue is solved by add the code below in the file: ..\Mageplaza\SocialLogin\Controller\Social\Callback.php

```
$param = $this->getRequest()->getParams();
        if(!isset($param['hauth_start']) && !isset($param['hauth_done']) && isset($param['code'])){
            $params['type'] = 'instagram';
            $params['_secure']= (bool) $this->apiHelper->isSecure();
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $urlInterface = $objectManager->create('\Magento\Framework\UrlInterface');
            $url = $urlInterface->getUrl('sociallogin/social/login', $params);
            return $this->_redirect($url);
        }
```

**Comment by obukhow** [comment]
Please re-open. Here are reproduce steps.
1. Visit instagram.com and log out from your account. Make sure you are not logged in instagram.
2. Visit your magento store. Try to login via instagram. It will ask you for a login and password. After logging in you have the error.

**Comment by anas-shehadeh** [comment]
re-open.
