### ISSUE TITLE
getting exception (opening backend admin) after install on v2.2.4

### ISSUE THREAD

**Issue by scottw-finao** [mageplaza/magento-2-social-login#109]
### Preconditions

1. Magento: v2.2.4
2. PHP: 7.0
3. MySQL: v14.14 dist 5.7.22
4. 

### Steps to reproduce
unzipped archive in magento root
deployed (magento setup:upgrade && magento setup:di:compile && magento:deploy:static-content)

### Expected result
1. plugin works

### Actual result
1 exception(s):
Exception #0 (Exception): Notice: Undefined index: id in /srv/magento-stest/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

Exception #0 (Exception): Notice: Undefined index: id in /srv/magento-stest/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63
#0 /srv/magento-stest/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php(63): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/srv/magento-st...', 63, Array)
#1 /srv/magento-stest/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Model\Config\Structure\Element\Iterator->setElements(Array, 'default')
#2 /srv/magento-stest/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Config\Model\Config\Structure\Element\Iterator\Tab\Interceptor->___callParent('setElements', Array)
#3 /srv/magento-stest/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Config\Model\Config\Structure\Element\Iterator\Tab\Interceptor->Magento\Framework\Interception\{closure}(Array, 'default')
#4 /srv/magento-stest/generated/code/Magento/Config/Model/Config/Structure/Element/Iterator/Tab/Interceptor.php(26): Magento\Config\Model\Config\Structure\Element\Iterator\Tab\Interceptor->___callPlugins('setElements', Array, Array)
#5 /srv/magento-stest/vendor/magento/module-config/Model/Config/Structure.php(146): Magento\Config\Model\Config\Structure\Element\Iterator\Tab\Interceptor->setElements(Array, 'default')
#6 /srv/magento-stest/generated/code/Magento/Config/Model/Config/Structure/Interceptor.php(24): Magento\Config\Model\Config\Structure->getTabs()
#7 /srv/magento-stest/vendor/magento/module-config/Model/Config/Structure.php(209): Magento\Config\Model\Config\Structure\Interceptor->getTabs()
#8 /srv/magento-stest/generated/code/Magento/Config/Model/Config/Structure/Interceptor.php(76): Magento\Config\Model\Config\Structure->getFirstSection()
#9 /srv/magento-stest/vendor/magento/module-config/Controller/Adminhtml/System/AbstractConfig.php(60): Magento\Config\Model\Config\Structure\Interceptor->getFirstSection()
#10 /srv/magento-stest/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Controller\Adminhtml\System\AbstractConfig->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /srv/magento-stest/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->___callParent('dispatch', Array)
#12 /srv/magento-stest/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /srv/magento-stest/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /srv/magento-stest/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /srv/magento-stest/generated/code/Magento/Config/Controller/Adminhtml/System/Config/Index/Interceptor.php(39): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->___callPlugins('dispatch', Array, NULL)
#16 /srv/magento-stest/vendor/magento/framework/App/FrontController.php(55): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /srv/magento-stest/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /srv/magento-stest/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#19 /srv/magento-stest/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /srv/magento-stest/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#21 /srv/magento-stest/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /srv/magento-stest/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#23 /srv/magento-stest/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#24 /srv/magento-stest/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#25 {main}

**Comment by scottw-finao** [comment]
most online resources say to check the system.xml file(s) but not knowing what the plugin is trying to do, I didn't see anything obviously amiss

**Comment by zebeel** [comment]
Did you install Mageplaza Module Core? If not please install it, the repo can be found here: https://github.com/mageplaza/module-core

**Comment by zebeel** [comment]
Close due to no response in 7 days.
