### ISSUE TITLE
Can you change default Valid OAuth redirect URIs to be HTTPS?

### ISSUE THREAD

**Issue by rationalbabe** [mageplaza/magento-2-social-login#111]
1. Magento: 2.2.5
2. PHP: 7.0
3. MySQL: 
4. 

### Steps to reproduce

1. Try to login using facebook login button from any page in Magento website
2. 
3. 

### Expected result

1. It should login correctly

### Actual result

1. You get the following error: "Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://"

**Comment by rationalbabe** [comment]
This was being set in a php file called "RedirectUrl" located in /var/www/html/vendor/mageplaza/<social login folder>/Block/System/
Which was further being read from a file called "Social.php" located in /var/www/html/vendor/mageplaza/<social login folder>/Helper/
Which was further being read from "Store.php" located in /var/www/html/vendor/Magento/Store/Model/

Bottom line is it was trying to read the value from the store config "web/secure/use_in_frontend" which was previously set to null. Updated this in the database using the following command:

UPDATE core_config_data SET value = 1 where path = 'web/secure/use_in_frontend';

And then flushed the cache

**Comment by zebeel** [comment]
This issue relates to the Facebook app. It requires the HTTPS.
Please read this documentation: http://docs.mageplaza.com/social-login-m2/how-to-configure-facebook-api.html

**Comment by zebeel** [comment]
What is the version you using? If it is outdated, please update the latest.
