### ISSUE TITLE
Magento CE 2.2.5 Google recaptcha not working with Social Login

### ISSUE THREAD

**Issue by ramindas** [mageplaza/magento-2-social-login#113]
### Preconditions

1. Magento: CE 2.2.5
2. PHP: 7.1
3. MySQL: Percona 5.6 

### Steps to reproduce

1. Installed 2FA and recaptcha using Magento composer.
2. Activated extension
3. Not working with Socil Login

### Expected result

1. recaptcha challenge on login screen

### Actual result

1. It says invalid recaptcha and challenge not showing in popup windows. it is working with backend without any issue

**Comment by MaxxLuong** [comment]
Hi
Thank you for your information.
The package "2FA and Recaptcha" not supported "multiple form captcha" in a page and Ajax form. Hence, we need a period of time to compatible with it for one to two weeks.
I will let you know when I completed this problem. Thank you.

**Comment by MaxxLuong** [comment]
Hi, 
Thank you for your information.
"2FA and Recaptcha" not supported "multiple form captcha" in a page and Ajax form. Hence, we need a period of time to compatible with it. I will let you know when I completed this problem. Thank you.

**Comment by jeredmilla** [comment]
Hi Is there an update to this?
