### ISSUE TITLE
Social Button is hidden & JavaScript load error.

### ISSUE THREAD

**Issue by VincentJorge** [mageplaza/magento-2-social-login#114]
Hi ,

I installed the social login module by Google, I made the configuration of the API key on my google account.

But now when I go to the login page:

- The button does not appear.
- Yet the HTML code is present, but hide.
-In the console, there is a JS file that can not be loaded.

-------------

I use:
Magento 2.2.5
PHP 7.1.19

------------
JS LOAD ERROR :
<img width="1279" alt="capture d ecran 2018-08-21 a 16 16 15" src="https://user-images.githubusercontent.com/23119894/44407102-911df000-a55d-11e8-86de-5b415283fe59.png">

HTML IS PRESENT BUT HIDDEN :
<img width="1253" alt="capture d ecran 2018-08-21 a 16 17 16" src="https://user-images.githubusercontent.com/23119894/44407175-b7dc2680-a55d-11e8-85ab-a55c9c87928b.png">

My config in back-office :
<img width="690" alt="capture d ecran 2018-08-21 a 16 17 55" src="https://user-images.githubusercontent.com/23119894/44407231-dc380300-a55d-11e8-989c-9f9379704560.png">
---
<img width="792" alt="capture d ecran 2018-08-21 a 16 18 16" src="https://user-images.githubusercontent.com/23119894/44407271-f40f8700-a55d-11e8-8ac4-29a84d2a56bb.png">
---
<img width="876" alt="capture d ecran 2018-08-21 a 16 18 21" src="https://user-images.githubusercontent.com/23119894/44407390-4781d500-a55e-11e8-88ff-f2726753da88.png">

**Comment by bien119** [comment]
Hi Vincent
To solve this issue, please grant permissions to the directory
- \pub\static\frontend\Magento\luma\en_US\Mageplaza_SocialLogin\js\view\social-buttons.js

If the 'social-buttons.js' doesn't exist on above directory, grant permissions with the path below.
- \app\code\Mageplaza\SocialLogin\view\frontend\web\js\view\social-buttons.js

Then run deploy in the command line.

**Comment by MaxxLuong** [comment]
Close due to no response in 7 days
