### ISSUE TITLE
Google Login Requires Verfification

### ISSUE THREAD

**Issue by Mohitmohan20** [mageplaza/magento-2-social-login#115]
Using the Google Login; google Confirmed; the app is trying to access User Contact Scope which is not required by for Sign In; hence Google Demands justification (Like Age, Birthday) Otherwise it says it cant ve approved; and while Sign In it displays an ugly message that App is not approved?

Is this the default behavior? OR any work around? Where can I which request is being sent to google

### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by MaxxLuong** [comment]
Hi, 

Can you provide me some the screenshot? Thanks

**Comment by Mohitmohan20** [comment]
per Google we App is requesting additional information (Like Age, *Manage*
Your Account) which it should NOT.

Where can I see the code where the App is requesting the scope?

This is issue is OPEN for 1 month now.

Can you please help?

**Comment by MaxxLuong** [comment]
Hi, 

There are two places declared the variable "scope".

..\app\code\Mageplaza\SocialLogin\Helper\Social.php. (in the function "getSocialConfig").
![image](https://user-images.githubusercontent.com/16910940/44760266-317ca180-ab68-11e8-885c-b80d8fad50e6.png)

..\lib\internal\Mageplaza\Hybrid\Providers\Google.php.
![image](https://user-images.githubusercontent.com/16910940/44760296-61c44000-ab68-11e8-9a50-413a4ce8b163.png)

You need to edit both files.

**Comment by Mohitmohan20** [comment]
Thank you.

SO which scope shall i give which is ONLY required for login?

**Comment by saunptit97** [comment]
Google Login in our Module Social Login has required user information as username, email, address.
