### ISSUE TITLE
Callback URL doesn't satify new Twitter App creation requirements

### ISSUE THREAD

**Issue by markxeasy** [mageplaza/magento-2-social-login#116]
As of the latest version of the [developer.twitter.com](https://developer.twitter.com/) app creation process the Callback URL given by the extension configuration isn't valid anymore. This is because Twitter doesn't allow query strings in a callback anymore, this is documented [here](https://developer.twitter.com/en/docs/basics/developer-portal/guides/callback-urls.html).

### Preconditions

1. Magento: 2.2.6
2. PHP: 7.1.20
3. MySQL: 5.7.23

### Steps to reproduce

1.  Install mageplaza/magento-2-social-login extension
2.  Go to Social Login configuration and copy the Callback URL given for the Twitter integration
3.  Try following the steps to create a new Twitter app on [developer.twitter.com](https://developer.twitter.com/)

### Expected result

1.  The creation of a Twitter app that will be used to login with a Twitter user on the Magento Store

### Actual result

1. The Callback URL is refused as it is invalid under the new requirements

**Comment by MaxxLuong** [comment]
Hi,
Thank for your information, we are checking it.

**Comment by JingZhaoyang2018** [comment]
I was troubled by it too

**Comment by MaxxLuong** [comment]
You can use the old app. I'm checking this issue and waiting for feedback from Twitter to create the new app. I will let you know when I updated anything.

**Comment by bien119** [comment]
I've created a new twitter app, then tested and debugged this issue.

To fix this, you just need to edit "Callback URL" in your app http://prntscr.com/kw1yla, remove query strings "**?hauth.done=Twitter**" in the URL.
Note that the URL end by "/".

Example:

- **Old Callback URL**: http://localhost.com/m225/sociallogin/social/callback/?hauth.done=Twitter

- **New Callback URL**: http://localhost.com/m225/sociallogin/social/callback/

**Comment by MaxxLuong** [comment]
Close due to no response in 7 days
