### ISSUE TITLE
How can we add "login" button on checkout page or any custom page?

### ISSUE THREAD

**Issue by m3alamin** [mageplaza/magento-2-social-login#117]
I want to display login button on checkout page. Is there any way to do that?

### Preconditions
1. Magento: 2.1.14

**Comment by Desmond-MagePlaza** [comment]
Isn't there is the login button right at the top right corner of the checkout page? http://prntscr.com/ktcpkg

**Comment by m3alamin** [comment]
Thanks for your reply @Desmond-MagePlaza 

Yes, There is Sign in button but that doesn't display the social login popup in checkout page. It works on other pages.

**Comment by Desmond-MagePlaza** [comment]
@m3alamin Thank you for the explanation.
I see that you want to add the social login function in the checkout cart. However, this particular feature is not supported in the free version of MagePlaza Social Login.
If you really need to add those social login buttons on the checkout page, please consider our Social Login Pro version. 
Also, you could take a look at MagePlaza's One Step Checkout extension; this module is fully integrated with Social Login Pro and it can boost the checkout process significantly

**Comment by m3alamin** [comment]
Thanks a lot. I will buy pro version if I find it useful. I am trying this on demo store right now. And I am using One Step Checkout extension for very very long time (From Magento version 1.7.x I guess).

Thanks.

**Comment by OPADA-Eng** [comment]
@m3alamin Could you please tell us how did you do that ? 
I have the same problem and I don't find ant solution.
Thanks
