### ISSUE TITLE
Social Login Error Google Plus Redirect

### ISSUE THREAD

**Issue by Krishnadcc** [mageplaza/magento-2-social-login#118]
**Valid OAuth redirect URIs**

404 error showing when redirecting from google plus

![error](https://user-images.githubusercontent.com/43240222/45489231-63555100-b781-11e8-812b-7591a250cf7f.png)

**Comment by bien119** [comment]
Did you add the SocialLogin library? you can find the library with the link below.

- https://github.com/mageplaza/magento-2-social-login-library

After that, follow these steps below to configure.

- https://docs.mageplaza.com/social-login-m2/index.html

- https://docs.mageplaza.com/social-login-m2/how-to-configure-google-api.html

**Comment by Krishnadcc** [comment]
I have copied the  SocialLogin library folder in root_folder/**lib**/internal/Mageplaze folder also upgrade the setup.
but the problem is still existing.

**Comment by MaxxLuong** [comment]
Hi,
The folder is wrong. It is "root_folder/lib/internal/**Mageplaza**", not root_folder/lib/internal/**Mageplaze**.
This is a screenshots in my local machine: [http://prntscr.com/ku8suc](http://prntscr.com/ku8suc).

**Comment by Krishnadcc** [comment]
My folder location is lib/internal/Mageplaza.
But it is not working.

**Comment by MaxxLuong** [comment]
Hi,
A little while ago, have you downloaded the library at
[https://github.com/mageplaza/magento-2-social-login-library](https://github.com/mageplaza/magento-2-social-login-library) Or 
[https://github.com/mageplaza/magento-2-social-login/tree/library](https://github.com/mageplaza/magento-2-social-login/tree/library) ?.

**Comment by MaxxLuong** [comment]
[https://github.com/mageplaza/magento-2-social-login-library](https://github.com/mageplaza/magento-2-social-login-library) is the old library.

**Comment by Krishnadcc** [comment]
Yes, I have downloaded it from this link 
https://github.com/mageplaza/magento-2-social-login/tree/library

**Comment by bien119** [comment]
After following these above steps, if you still get this error, you can create a ticket here (https://www.mageplaza.com/contact.html). Our team will help you check this issue.

**Comment by gaurangpadhiyar007** [comment]
Has anybody resolved this issue?? It is still persisting in module.. Please help it's urgent.

**Comment by gaurangpadhiyar007** [comment]
Hello @Krishnadcc @bien119 @MaxxLuong @barbazul ,

After debugging , i have found this 
**ErrorDocument 403 /pub/errors/404.php**
line in .htaccess which redirect **403 error** in **404 request page**.

So it is not an issue of error: 404 page not found but actually it is **403 error**. 

In this case you must have to contact your server administrator or hosting provider.

Hope this help someone in future.
And if you find redirection issue in magento 2 go thorough [this ](https://coffeewithmagento.blogspot.com/2018/09/magento-continues-redirection.html)
