### ISSUE TITLE
Social buttons missing on authentication popup during checkout

### ISSUE THREAD

**Issue by crankycyclops** [mageplaza/magento-2-social-login#119]
I've noticed that social buttons are missing in a couple of places. One is the create account popup (although if I don't use the popup and instead use the create account page, they're there, so that's not too big of a deal for me.) The other is when you attempt to checkout without having logged in. The social buttons are missing here, and so you have to login with a username and password.

Is this something that was just overlooked, and if so, will it be added to an upcoming release? If not, no worries. I understand that this module is free, so I'm not going to complain :)

Thank you!

Module version: 2.7.1

Magento version: 2.2.6
PHP: 7.1
MySQL: MariaDB 10.2

Steps to reproduce:
1. Do not login
2. Add a product to your cart
3. Attempt to checkout

Expected result:

Social login buttons will appear in the authentication popup.

Actual result:

No social buttons are added to the popup, and the user has to use a username and password.

**Comment by crankycyclops** [comment]
I guess for authentication during checkout, if you click the "Create Account" button, you can get to the social login buttons, so that's not as much of an issue as I thought.

**Comment by MyoDaisy** [comment]
You can choose Customer Authentication Popup in Configuration > Social Login > General > Show Social Login Buttons on to show social button in authentication popup (https://prnt.sc/la7a9r)
we didn't add the social button into the create account popup yet. But if you want to add it, I have customized a new module for you. You can download and reinstall it https://drive.google.com/file/d/1o1_8_OaTAUFXBP4ymAPvYo2T7TCIaBMu/view?usp=sharing

**Comment by crankycyclops** [comment]
> You can choose Customer Authentication Popup in Configuration > Social Login > General > Show Social Login Buttons on to show social button in authentication popup (https://prnt.sc/la7a9r)
> we didn't add the social button into the create account popup yet. But if you want to add it, I have customized a new module for you. You can download and reinstall it https://drive.google.com/file/d/1o1_8_OaTAUFXBP4ymAPvYo2T7TCIaBMu/view?usp=sharing

Oh wow, thank you! :)
