### ISSUE TITLE
Choose the redirection page after successful login

### ISSUE THREAD

**Issue by metamasterplay** [mageplaza/magento-2-social-login#12]
Hello,

I've noticed that after a successful login the customer is automatically redirected to its dashboard (customer/account). Looking through your code I've found that you have already worked on this functionality by implementing the function `_loginPostRedirect()` in `Controller/AbstractSocial.php`. I have tested it and it seems to work great, except for:

- There is no frontend interface for the option `general/select_redirect_page`. So the redirect option must be hardcoded in the file. I wish I could implement it but I don't have much developing skills in Magento.
- In case 3, `$url = $this->session->getCurrentPage()` redirects to the current url used to request social login, for example `/sociallogin/facebook/login/`. This can be easily corrected by using instead `$this->_redirect->getRefererUrl()` which redirects to where the customer was.

Good luck and let me know if you need any further testing.

**Comment by imsamthomas** [comment]
Thanks @metamasterplay,
We have noted and our team will implement this soon.

**Comment by SilvanLaroo** [comment]
@imsamthomas we're also looking for this feature, is this already implemented?

**Comment by SilvanLaroo** [comment]
@imsamthomas could you give us an update on this issue?

**Comment by Rutvee123** [comment]
Have any way to check that reffrelUrl was product[page or not?

**Comment by poveu** [comment]
Hi, we're still unable to set the redirect page - so (when not using popup login) successful logging in always redirects to 'customer/account/' instead of the page the customer came from.

**Comment by bien119** [comment]
@metamasterplay @SilvanLaroo 
FYI, Our team has developed this feature on social login professional version. It allows redirecting to the configured URL after successful login.
