### ISSUE TITLE
Bug: Google login doesn't work when adding to your wishlist as an unauthenticated user

### ISSUE THREAD

**Issue by crankycyclops** [mageplaza/magento-2-social-login#120]
Here's an issue I've noticed during testing. I'm not sure if it's just the way my instance of Magento is configured, but if I attempt to add a product to a wishlist as an unauthenticated user and then try to login using Google and the social login plugin, after successful Google authentication, I'm redirected back to the login page, and Magento authentication never takes place.

I've observed no network or javascript errors. I've only tested this with Google so far.

I've tested the same workflow with an ordinary Magento user account, and authentication works as expected.

I'm on Magento 2.2.6, with PHP 7.1 and MariaDB 10.2.

Steps to reproduce:

1. Make sure you're not authenticated
2. Attempt to add a product to your wish list
3. When you're redirected to the login page, attempt to login via Google
4. Observe that Google authentication is successful, but Magento authentication is not (there are no errors, it just never logs in)

Testing this with other workflows (such as adding to your cart and trying to checkout as an unauthenticated user) seem to work just fine.

If you guys can't reproduce this, let me know and I'll try to dig deeper.

**Comment by MyoDaisy** [comment]
I followed the steps that you instructed to reproduce the problem. But I still able to login properly with Magento authentication. 
So could you please explain your problem in more details or send me a video on how to reproduce the problem.

**Comment by phuongtt1991** [comment]
Hi,
I will close this issue. If you have still any problem with this issue, please create a ticket or contact with live chat team of Mageplaza.
Thank you very much and have a nice day!
Matthew

**Comment by crankycyclops** [comment]
Hi, sorry I didn't reply. I've been through a series of international flights and haven't had a chance to take a screen capture of the problem. I'll try to test again over the weekend to verify, and if it's still a problem, I'll post a new github issue with a link to a video illustrating the problem.

Thank you!

**Comment by rendyep** [comment]
hi @crankycyclops did you solve this issue? I have the same issue, after logging in via social login, I can't get the product added to wishlist.

**Comment by crankycyclops** [comment]
Hey @rendyep, not yet. I've had to step away from code for a while to focus on other concerns, so I haven't had a chance to dig into this more.
