### ISSUE TITLE
Move position button login to other location

### ISSUE THREAD

**Issue by tuanhai363** [mageplaza/magento-2-social-login#122]
I can't move button to other page, I did use absolute to move button, however when screen responsive, it not good.
send for me, any thing idea

### Preconditions

1. Magento: 2.3
2. PHP: 7.1

### Actual result

1. [Screenshot, logs]
![screen shot 2018-11-13 at 2 47 14 pm](https://user-images.githubusercontent.com/35917096/48398334-0eb75d80-e753-11e8-8464-27068717aa06.png)
![screen shot 2018-11-13 at 2 47 49 pm](https://user-images.githubusercontent.com/35917096/48398365-22fb5a80-e753-11e8-89be-60e9e8d1730b.png)

**Comment by bien119** [comment]
Hi Tuan Hai,

You are using the css properties, aren't you?

Please follow my instruction.
[element {
          position:absolute;
          top: xpx;
          left: ypx;
}](url)
Note that:

- element is class or Id of social button elements.

- x,y value depends on your theme.

Here is a test on my local machine. Take a look at the result.

- http://prntscr.com/lhpn7g

**Comment by tuanhai363** [comment]
Hi bien119
I did use method call function of mageplaza:
<?php

$availableSocials = $block->getAvailableSocials();

    ?>
  <div class="social-login-authentication-channel account-social-login">
    <div class="block-content">
        <?php foreach ($availableSocials as $key => $social): ?>
          <div class="actions-toolbar social-btn social-btn-actions-toolbar <?= $key ?>-login">
            <a class="btn btn-block btn-social btn-<?= $block->getBtnKey($key) ?>"
               data-mage-init='{"socialProvider": {"url": "<?php echo $social['login_url'] ?>", "label": "<?php echo __('Login By %1', $social['label']) ?>"}}'>
              <span class="fa fa-<?= $block->getBtnKey($key) ?>"> </span>
                <?php echo __('Sign in with %1', $social['label']) ?>
            </a>
          </div>
        <?php endforeach; ?>
    </div>
  </div>

<?php $availableSocials = $block->getAvailableSocials(); ?>
<?php var_dump($availableSocials)?>


and config in admin 
![screen shot 2018-11-19 at 8 32 28 pm](https://user-images.githubusercontent.com/35917096/48762782-5b181580-ecde-11e8-8785-66407447a7bf.png)
![screen shot 2018-11-13 at 2 47 14 pm](https://user-images.githubusercontent.com/35917096/48762787-5e130600-ecde-11e8-8741-1b76fcb1f1d5.png)


this work for me

**Comment by tuanhai363** [comment]
Hi, because your buttons can't move follow idea, I think that is not good :))

**Comment by bien119** [comment]
Hi,
Your approach is not good. I think you shouldn't write it in Magento_Customer module.
You can create a ticket with the link below:

- https://www.mageplaza.com/contact.html

Our team will find out the best way to help you.

**Comment by tuanhai363** [comment]
Now, I have problem with SMTP send mail, I can not send mail from local and
server,
I have notice sendmail success, but I check Inbox do not have
Can you help me?

===============================================
*Phan Tất Hải (Mr.)*

Professional Staff : CNTB 2
KIM PHAT real estate company* – Tân Bình 2*
Tòa nhà Kim Phát
74 Xuân Diệu, P.4, Q.Tân Bình, TP.HCM.
Tel.: 0838. 688 999

Mobile  :  0984947714
Email      : tuanhai363@gmail.com
Website  :http://diaockimphat.vn <http://www.dai-ichi-life.com.vn/>

**Comment by bien119** [comment]
Hi,
Please create a ticket with the link below. Our support team will help you.
Your question is not clear. There are many reason why SMTP cannot send mail.
It's easier for us with support ticket freshdesk chanel.
- https://www.mageplaza.com/contact.html

**Comment by tuanhai363** [comment]
I did send feedback, please check!

======================== =======================
*Phan Tất Hải (Ông.)*

Nhân viên chuyên nghiệp  : CNTB 2
Công ty bất động sản KIM PHÁT * - Tân Bình 2*
Tòa nhà Kim Phát
74 Xuân Diệu, P.4, Q.Tân Bình, TP.HCM .
Điện thoại:  0838. 688 999

Điện thoại di động: 0984947714 Email:  tuanhai363@gmail.com Website:
http://diaockimphat.vn <http://www.dai-ichi-life.com.vn/>
<tuanhai363@gmail.com>
<http://www.dai-ichi-life.com.vn/>

**Comment by phuongtt1991** [comment]
Hi,
If you create a new ticket for this issue, we will support you via our ticket system. I will close this issue.
Thank you and have a nice day!
