### ISSUE TITLE
Product Is not Added To Wishlist After Logging In Via Social Login

### ISSUE THREAD

**Issue by rendyep** [mageplaza/magento-2-social-login#125]
I think the title is clear enough to describe the issue. The data below may help investigating the problem.

### Preconditions
1. Magento: 2.2.6
2. PHP: 7.1.24
3. MySQL: 5.6.38

### Steps to reproduce
1. Visit product page as a guest
2. Click **Add to wishlist** button
3. The guest user is redirected to login page
4. Use any configured social login that is available

### Expected result
After logged in successfully:
1. The product is added to wishlist
2. User is redirected to wishlist page

### Actual result
After logged in successfully:
1. The product is not added to wishlist
2. User is not redirected to wishlist page

**Comment by Arthas78** [comment]
We have encountered this problem before you can follow here
https://github.com/mageplaza/magento-2-social-login/issues/120

**Comment by rendyep** [comment]
No, it's completely a different issue. I'm able to login peoperly. My issue here is the product that is intended to be placed to wishlist is not added.

I have got reply from Magento support: this feature is not available yet, and may become available in the next release.
