### ISSUE TITLE
google pluse register sometimw working sometime not working

### ISSUE THREAD

**Issue by rakeshdonga** [mageplaza/magento-2-social-login#127]
when i am google plus create an account and some time redirect account page but **mostly time redirect login page** not working properly

**Comment by bien119** [comment]
Hi @rakeshdonga,
When redirecting to login page, is Customer logged in or not? Please disable full page cache and check it again.

**Comment by bien119** [comment]
@rakeshdonga, Did you try to clean the cache?

**Comment by rakeshdonga** [comment]
yes i have try allready

**Comment by bien119** [comment]
@rakeshdonga, please try to login with URL without params. 
For example: Your login pate URL is
https://yoursite.com/customer/account/login/referer/aHR0cHM6Ly9sb2NhbGhvc3QuY29tL21hZ2VudG8yMzAvY3VzdG9tZXIvYWNjb3VudC9jcmVhdGUv/

Eliminate the param and you can try with https://yoursite.com/customer/account/login/
Let's me know if it works.

**Comment by rakeshdonga** [comment]
when i am register using google pluse at that time redirect to your like : 1st link

**Comment by bien119** [comment]
@rakeshdonga, you can follow the path below

- mageplaza\SocialLogin\Controller\Social\AbstractSocial.php

You can add the code like in the screenshot (http://prntscr.com/mbeviz) to make sure the URL redirect is true.
Here is the code: `if($object->getUrl() !== null)`

**Comment by rakeshdonga** [comment]
thanks @bien119  
working for me
