### ISSUE TITLE
Facebook login not working

### ISSUE THREAD

**Issue by ktsixit** [mageplaza/magento-2-social-login#129]
### Preconditions
1. Magento 2.2.4
2. Social Login 2.3.7

### Steps to reproduce
1. Login with Facebook

### Expected result
1.  Successful login 

### Actual result
1. After submitting email/passowrd, I'm getting error
Notice: Undefined offset: 1 in lib/internal/Mageplazza/SocialLogin/Facebook/Http/GraphRawResponse.php on line 108

I checked the file. In function setHttpResponseCodeFromHeader()
$rawResponseHeader is "HTTP/2 200"
$match is empty array

How can I fix this?

**Comment by bien119** [comment]
Please open: 

- lib/internal/Mageplazza/SocialLogin/Facebook/Http/GraphRawResponse.php

 on line 107
Current code:

* preg_match('|HTTP/\d.\d\s+(\d+)\s+.*|',$rawResponseHeader, $match);

You can edit the code to:

* `preg_match('/HTTP\/\d(?:\.\d)?\s+(\d+)\s+/',$rawResponseHeader, $match);`

You can refer issue #124

**Comment by bien119** [comment]
@ktsixit I'll close this issue (No response in 7 days). Hope you the best result with my solution.
