### ISSUE TITLE
[Improvement] Add social login block to Magento 2 default authentication popup

### ISSUE THREAD

**Issue by metamasterplay** [mageplaza/magento-2-social-login#13]
Hello,

I've been trying to add the social login block to the default Magento 2 authentication block but without any success. For reference the default checkout popup login is this one:
![image](https://cloud.githubusercontent.com/assets/12763123/23331743/fe18abdc-fb63-11e6-9942-9e52f4fa7048.png)

Steps to reproduce:

- Visit the website while being logged off

- Add items to cart

- In cart click **Go to Checkout**

Expected result:

- Magento default login popup with social options

Actual result:

- Magento default login popup with no social options

I have tried adding this code to `default.xml` inside the `<body>` tag but without any success:
`<referenceBlock name="authentication-popup">
        <block class="Mageplaza\SocialLogin\Block\Popup\Authentication\Social" before="-" ifconfig="sociallogin/general/is_enabled" name="social-login-popup-authentication-social-login" template="Mageplaza_SocialLogin::form/social.phtml" cacheable="true"/>
</referenceBlock>`

Thanks again for the great extension.

**Comment by imsamthomas** [comment]
Thanks, We have noted on our internal system.
