### ISSUE TITLE
Login Popup not working on IE browser

### ISSUE THREAD

**Issue by karangar** [mageplaza/magento-2-social-login#131]
### Preconditions

1. Magento: 2.2.6
2. PHP: 7.1

### Steps to reproduce

1. Enable login popup
2. Go To IE Browser
3. Click on "Sign In" popup will display 

### Expected result

1. Click on the Log In button display required field error.
2. After adding correct Input and login successfully

### Actual result

1. Click on the Log In button not display required field error.
2. After adding correct Input and login not working.
![screenshot-192 168 11 128-2019 02 08-12-28-03](https://user-images.githubusercontent.com/34768419/52463601-77b94080-2b9d-11e9-96f0-9609f140e71e.png)

**Comment by bien119** [comment]
hi @karangar. IE Browser doesn't support 'includes' method.
You can replace it by 'indexOf' method to make them compatible.

Path: Mageplaza/SocialLogin/view/frontend/web/js/popup.js
line 159 (http://prntscr.com/midhe1), 330 (http://prntscr.com/midhnq)

**Comment by karangar** [comment]
Thanks @bien119 
It's Working.

**Comment by bien119** [comment]
Great! I'm going to close this issue.
