### ISSUE TITLE
facebook login https

### ISSUE THREAD

**Issue by vaseemishak** [mageplaza/magento-2-social-login#132]
Facebook login enforce https  validoatuh utl , while in module you cant edit the valid oauth url from http to https

### Preconditions
1. Magento: 2.2.3

**Comment by bien119** [comment]
Facebook requires using https. You have to register the certificate to use https. Our extension doesn't have the responsibility to edit http to https.

**Comment by vaseemishak** [comment]
sorry i must explain it briefly.
The config option named as "Valid OAuth redirect URIs" in module configration show http url  and you cant edit it , but facebook need https url , my site as already https .

**Comment by vaseemishak** [comment]
sorry my bad , in magento config the domain was not https , it was http v, after making it https its work ,thanks
