### ISSUE TITLE
Social login pupup fail in magento 2.2.7

### ISSUE THREAD

**Issue by joaquin-becerra** [mageplaza/magento-2-social-login#133]
### Preconditions
1. Magento: 2.2.7
2. PHP: 7.0

### Steps to reproduce
1. Install the extencion
2. Enable the social login
3. Enable the Popup Login functionality

If the popup option is active:

 Store > Configuration > Social Login > Use Popup Login = true

I get this exception:
`
Exception #0 (ReflectionException): Class Magento\Captcha\Model\Zend does not exist
#0 /var/www/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Captcha...')
#1 /var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Captcha...')
(...)
#21 /var/www/vendor/mageplaza/magento-2-social-login/view/frontend/templates/popup.phtml(26): Magento\Framework\View\Element\AbstractBlock->getChildHtml('popup.authentic...')
`

Thanks

**Comment by bien119** [comment]
I was testing on M2.2.7 and I saw no errors like what you got. So, please make sure the core-module was installed. You can find how to install/upgrade it with the link below.

- https://github.com/mageplaza/module-core

**Comment by joaquin-becerra** [comment]
Hi bien119, thanks for your reply.

Yes, I have installed the extension, via composer:

 composer require mageplaza/magento-2-social-login
 php bin/magento setup:upgrade
 php bin/magento setup:static-content:deploy

This install the extensions:

 vendor/Mageplaza/magento-2-social-login
 vendor/mageplaza/module-core
 vendor/mageplaza/module-google-recaptcha
 vendor/mageplaza/module-reports
 vendor/mageplaza/module-smtp
 vendor/facebook/graph-sdk
 vendor/paypal/rest-api-sdk-php

I disabled this in the app/etc/config.php

        'Mageplaza_GoogleRecaptcha' => 0,
        'Mageplaza_Reports' => 0,
        'Mageplaza_Smtp' => 0,

This is the full stack exception when I go tho the home with the 'Use Popup Login' flag enabled:

1 exception(s):
Exception #0 (ReflectionException): Class Magento\Captcha\Model\Zend does not exist

Exception #0 (ReflectionException): Class Magento\Captcha\Model\Zend does not exist
#0 /var/www/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Captcha...')
#1 /var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Captcha...')
#2 /var/www/vendor/magento/framework/ObjectManager/Factory/Compiled.php(100): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Captcha...')
#3 /var/www/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Captcha...', Array)
#4 /var/www/vendor/magento/module-captcha/Model/CaptchaFactory.php(37): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Captcha...', Array)
#5 /var/www/vendor/magento/module-captcha/Helper/Data.php(100): Magento\Captcha\Model\CaptchaFactory->create('Zend', 'user_login')
#6 /var/www/vendor/magento/module-captcha/Block/Captcha.php(49): Magento\Captcha\Helper\Data->getCaptcha('user_login')
#7 /var/www/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Captcha\Block\Captcha->_toHtml()
#8 /var/www/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#9 /var/www/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('social-login-ca...')
#10 /var/www/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('social-login-ca...')
#11 /var/www/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout->renderElement('social-login-ca...', true)
#12 /var/www/vendor/mageplaza/magento-2-social-login/view/frontend/templates/popup/form/authentication.phtml(55): Magento\Framework\View\Element\AbstractBlock->getChildHtml('login.captcha')
#13 /var/www/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/vendor...')
#14 /var/www/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Mageplaza\SocialLogin\Block\Form\Login), '/var/www/vendor...', Array)
#15 /var/www/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/vendor...')
#16 /var/www/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#17 /var/www/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#18 /var/www/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('social-login-po...')
#19 /var/www/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('social-login-po...')
#20 /var/www/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout->renderElement('social-login-po...', true)
#21 /var/www/vendor/mageplaza/magento-2-social-login/view/frontend/templates/popup.phtml(26): Magento\Framework\View\Element\AbstractBlock->getChildHtml('popup.authentic...')
#22 /var/www/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/vendor...')
#23 /var/www/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Mageplaza\SocialLogin\Block\Popup), '/var/www/vendor...', Array)
#24 /var/www/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/vendor...')
#25 /var/www/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#26 /var/www/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#27 /var/www/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('social-login-po...')
#28 /var/www/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('social-login-po...')
#29 /var/www/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('social-login-po...', false)
#30 /var/www/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('content', false)
#31 /var/www/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('content')
#32 /var/www/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('content', false)
#33 /var/www/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main', false)
#34 /var/www/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('main')
#35 /var/www/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('main', false)
#36 /var/www/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('columns', false)
#37 /var/www/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#38 /var/www/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('columns', false)
#39 /var/www/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#40 /var/www/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#41 /var/www/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('main.content', false)
#42 /var/www/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#43 /var/www/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#44 /var/www/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#45 /var/www/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('root', false)
#46 /var/www/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('root')
#47 /var/www/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout->renderElement('root')
#48 /var/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#49 /var/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#50 /var/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#51 /var/www/generated/code/Magento/Framework/View/Layout/Interceptor.php(39): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#52 /var/www/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#53 /var/www/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#54 /var/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#55 /var/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#56 /var/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#57 /var/www/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#58 /var/www/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#59 /var/www/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#60 /var/www/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#61 {main}

Regards

**Comment by bien119** [comment]
@joaquin-becerra when disabling the "Use popup login". Did you get the errors on the home page?

**Comment by joaquin-becerra** [comment]
No, if the popup is disabled there is not error.

Regards

**Comment by bien119** [comment]
@joaquin-becerra are you using social login standard or professional?
From the errors log, it's related to captcha. Do you have other captcha extension installed with us?

**Comment by joaquin-becerra** [comment]
Hi @bien119 

 Yes I'm using the standard plugin for social login.

 I gess that is usin the default magento module: https://github.com/magento/magento2/tree/2.2/app/code/Magento/Captcha

Regards

**Comment by bien119** [comment]
@joaquin-becerra You can try to disable the captcha module and try to use the popup again.
This test could be able to find the main cause made your issue.

**Comment by bien119** [comment]
@joaquin-becerra I'll close this issue (no response in 7 days). Hope you find the best solutions to solve it.
