### ISSUE TITLE
Composer require

### ISSUE THREAD

**Issue by sonbui00** [mageplaza/magento-2-social-login#136]
Please remove unnecessary module on composer require, I think I can run without mageplaza/module-smtp, mageplaza/module-reports

**Comment by bien119** [comment]
@sonbui00 here is the syntax to install extension via composer.

- composer require mageplaza/module-modulename

for example: composer require mageplaza/module-smtp
You said that **remove unnecessary module on composer require**. Sorry I don't get your mind 100%.
If you want to remove those extension, you just need to run the commands below:

- rm -rf vendor/mageplaza/module-smtp

- rm -rf vendor/mageplaza/module-reports

- composer dump-autoload

**Comment by bien119** [comment]
@sonbui00 This issue will be closed (no response in 7 days). Hope you have the best result with my solution.
