### ISSUE TITLE
Wrong Command

### ISSUE THREAD

**Issue by NIDHINgl** [mageplaza/magento-2-social-login#137]
given command is "composer require mageplaza/mmodule-smtp" but it's wrong please change it to "composer require mageplaza/module-smtp"

this page [https://docs.mageplaza.com/smtp-m2/install.html](url)
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by bien119** [comment]
Thank you for your information. That is a mistake in typing. Our team will fix it as soon as possible.

**Comment by bien119** [comment]
It was fixed. I'll close this issue.

**Comment by NIDHINgl** [comment]
Ok

**Comment by NIDHINgl** [comment]
Hey,

I just signed the petition "Stop the burning of the Amazon Rainforest!" and
wanted to see if you could help by adding your name.

Our goal is to reach 4,500,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/RPvJJcmQHZ

Thanks!
NIDHIN
