### ISSUE TITLE
Facebook login button doesn't comply with Facebook's policies

### ISSUE THREAD

**Issue by crankycyclops** [mageplaza/magento-2-social-login#138]
Today, I received a complaint from Facebook stating that my login with facebook button didn't comply with their policies.

Here's the exact email I received:

Hi,

In working to create a great Platform experience for everyone, we ask developers to ensure the apps they build comply with our Platform Policies. Your app APP NAME  (AppId: MY_APP_ID) doesn't comply with the following:

Platform Policy 8.3: Use a clearly branded "Login with Facebook" button and follow the Facebook Brand Guidelines: https://www.facebookbrand.com/.

Your Login button doesn't properly reference Facebook. To fix this issue, you should always use our official SDK for Login. For more information on Login best practices, check out the Login section of our developer documents: https://developers.facebook.com/docs/facebook-login/best-practices#buttondesign.

You can access the full list of our Platform Policies here: https://developers.facebook.com/policy/.

**Comment by crankycyclops** [comment]
After going back and forth with Facebook's support team, I was able to resolve the issue by overriding the form/social.phtml template in my custom theme and selectively replacing your Facebook button with the PNG button Facebook wants me to use here: https://developers.facebook.com/docs/facebook-login/best-practices#buttondesign

You can see a screenshot of how it appears on my page here: 
![resolved](https://user-images.githubusercontent.com/2059345/56076027-9ae1b580-5dc3-11e9-9f3f-ad4ab24f0bd1.jpg)

In my experience with Facebook support, they tend to be very inflexible with their requirements, and while they might technically say you can build your own button if it complies with the required look and feel, in practice, if you don't match their template, you're going to get a warning from them. Also, their requirements forbid you from modifying their logo, and I noticed you guys are using a styled ASCII 'F' in place of a Facebook image.

It would be a good idea for you guys to replace your Facebook login button with theirs in order to prevent your users from getting their Facebook accounts suspended.

**Comment by AigarsMurins** [comment]
Encountered same issue. Is there a patch in works? Asking since Facebook is asking us to make changes till 2019-04-22 . Otherwise we will need to make custom changes.

**Comment by bien119** [comment]
@crankycyclops You just need to change the facebook logo button to satisfy Facebook's policy requirement, Don't you? If yes, Our team will make an update soon @AigarsMurins.

**Comment by AigarsMurins** [comment]
@bien119 Is it possible to give us some what of a time frame on when patch will be available?

**Comment by crankycyclops** [comment]
@bien119, that's correct. Once I replaced the button, Facebook was happy.

**Comment by bien119** [comment]
@crankycyclops Thank you.
@AigarsMurins You can find the patch with the link below:

- https://drive.google.com/file/d/1exQewawoY7JHeVtMM5h5Jw3JL72mllSN/view?usp=sharing
Screenshot: 

- http://prntscr.com/ne190z

- http://prntscr.com/ne19ba

**Comment by bien119** [comment]
I'll close this issue. Hope you have the best result with my solution.
