### ISSUE TITLE
Uncaught TypeError: headerLink.magnificPopup is not a function.(popup.phtml)

### ISSUE THREAD

**Issue by msliman** [mageplaza/magento-2-social-login#14]
I have this javascript error in my console. Please help.

### Preconditions

1. Magento: 2.1.5
2. PHP:  7
3. MySQL: 5.6
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by haitv282** [comment]
Hi there,

To solve this issue, please upgrade our core module `https://github.com/mageplaza/core-m2`.
