### ISSUE TITLE
master branch is currently broken

### ISSUE THREAD

**Issue by juhanihaapala** [mageplaza/magento-2-social-login#141]
### Steps to reproduce

1. Install magento-2-social-login with version dev-master
2. Go to your site

### Expected result

1. Everything should work

### Actual result

1. Server will throw 500 error with message:
`1 exception(s): Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Mageplaza\SocialLogin\Block\Form\Register::isGdprProEnabled`

Reason for this is because in latest merge there is a commit which removes that method https://github.com/mageplaza/magento-2-social-login/pull/140/commits/35c2c38cedf99ca5aeec8248dde4f5bf50fef735#diff-832f3180f54675079ad6013089ed1373L38 but it is still in here https://github.com/mageplaza/magento-2-social-login/blob/35c2c38cedf99ca5aeec8248dde4f5bf50fef735/view/frontend/templates/popup/form/create.phtml#L190

**Comment by Desmond-Mageplaza** [comment]
Hi juhanihaapala,
Thank you for raising this issue.
We are currently in code sanitation process so there will be some mishaps.
We will fix this problem as soon as possible and update the repository in our next commit.
Thank you

**Comment by Desmond-Mageplaza** [comment]
Hi @juhanihaapala
The problem has been resolved with the latest commit.
Please take a look at the module repository

**Comment by juhanihaapala** [comment]
Looks like someone made new release before the fix so now the tag 2.7.5, which composer uses by default, is broken and master branch is fixed.
https://packagist.org/packages/mageplaza/magento-2-social-login#2.7.5

**Comment by Desmond-Mageplaza** [comment]
Hi @juhanihaapala
I addressed this issue to my supervisor and he did fix the problem and create a new release version.
Since the master branch is working properly again, I will close this Github issue.
Thank you for using Mageplaza extension service.
