### ISSUE TITLE
VK Authorization is Broken

### ISSUE THREAD

**Issue by obukhow** [mageplaza/magento-2-social-login#143]
Then getting user information from social network customer see the error

    Invalid request: versions below 5.00 are deprecated.
    Version param should be passed as "v". "version" param is invalid and not supported.
    For more information go to https://vk.com/dev/version_update_2.0

**Comment by Arthas7895** [comment]
Thank you for your information. We will check social login with the VK provider and will upgrade it ASAP.
Thank you again for your contributions to the module

**Comment by Desmond-Mageplaza** [comment]
Hi @obukhow 
Your pull request has been processed and merged by our manager so I will close this issue.
Thank you for your contribution.
