### ISSUE TITLE
Someone has stolen your free extensions

### ISSUE THREAD

**Issue by magefan** [mageplaza/magento-2-social-login#145]
Hello,

Check this page 
https://www.magetop.com/magento-2-social-login-extension.html

Looks like someone use Mageplazza social login, and say that they developed it.
https://www.mageplaza.com/magento-2-social-login-extension/
They also use your product reviews.

Stealing is not good and using other companies reviews is not good either, so we decided to let you know about this company and what they do with your product.

If you are a developer and read this, please forward this to your manager.

Best regards,
Magefan team

**Comment by Desmond-Mageplaza** [comment]
Hi @magefan,
I would like to express my profound gratitude for informing us about this situation.
I will definitely forward this issue to my manager to tackle this problem.

I also notice from their demo site that most of our free extension is stolen as well.

Once again, thank you for the information and thank you for keeping the integrity of Magento 2 Extension Builders Community

**Comment by Desmond-Mageplaza** [comment]
Hi again,
Our manager is currently aware of the problem and we have filed a report to MageTop domain, hosting provider as well as Paypal and Magento 2 Community.
I really hope some actions will be taken soon to prevent such behaviors.

Once again, thank you for reporting this problem.
Since we have responded to this violation, I will close this issue.
Wish you a lovely day!

**Comment by magefan** [comment]
@Desmond-Mageplaza , what let you know that we have found one another website that shares your extension as their own
https://www.magebest.com/magento-2-social-login-extension.html
please also check some their other extension as they may be a copy of yours
https://www.magebest.com/magento-extensions.html

Please forward this to your manager.
