### ISSUE TITLE
Loggin via LinkedIn is no longer available under v1 APIs

### ISSUE THREAD

**Issue by incosy** [mageplaza/magento-2-social-login#147]
### Preconditions

1. Magento: 2.3
2. PHP: 7.1.30
3. MySQL: 5.7.27

### Steps to reproduce

1. Install the extension.
2. Enable it from the admin panel.
3. Enable LinkedIn and fill Id client and secret client
4. try to get identified with Linkedin

### Expected result

1. Get connected

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/53898545/62692366-d76b9980-b9d0-11e9-929c-fa28e765c9eb.png)

**Comment by Victor-Mageplaza** [comment]
Hi @incosy 

Thank you! We have been reported on this error.
Currently, the update is being tested before being released.
If this error affects your use, please create a ticket through the support system so we can help you.

**Comment by Victor-Mageplaza** [comment]
Hi @incosy 
Since you were unable to respond within the time range, I will close this issue.
If the problem still persists, you can contact us via the support portal.
Thank you.
