### ISSUE TITLE
Un-necessary packages installing

### ISSUE THREAD

**Issue by cjnewbs** [mageplaza/magento-2-social-login#148]
I have installed this module and see there are 3 other modules that also get installed. These do not appear to be dependancies of the social login module. Is this intended behaviour or were they included in the `composer.json` accidentally? Can anyone confirm that if I were to add these packages to the `replace` section of composer to prevent installation that the module will still work as expected?

### Preconditions
Latest release of `mageplaza/module-google-recaptcha`

### Steps to reproduce
Run `composer require mageplaza/module-google-recaptcha`

### Expected result
Only necessary dependancies are installed

### Actual result
The following modules are also installed. The do not appear to be necessary dependancies.
mageplaza/module-smtp
mageplaza/module-google-recaptcha
mageplaza/module-reports

**Comment by Victor-Mageplaza** [comment]
Hi @cjnewbs 
I'm Victor from Mageplaza. I would like to answer your question as follows:
-  Our SocialLogin module only needs a Core module to operate
- Listing modules in the composer file is a list of compatible extensions and functional plugins for the SocialLogin module
Hope my answer can help you. Thank you!

**Comment by cjnewbs** [comment]
Hi Victor,

Thanks for the reply. Maybe it would be better to place these in the `suggest` section of the `composer.json` to avoid installing them if they are not needed? I'm happy to open a PR after I test it if this would be helpful.

If anyone else is wondering I have tested locally and adding the other packages to the`replace` section of `composer.json` worked just fine if you do not need the additional modules. But as always test before deploying. Example below:
```
  "replace": {
    "mageplaza/module-smtp": "*",
    "mageplaza/module-google-recaptcha": "*",
    "mageplaza/module-reports": "*"
  },
```

**Comment by Victor-Mageplaza** [comment]
Hi @cjnewbs 
I sincerely thank you for your contributions.
We will note and make reasonable changes in future versions.

**Comment by Victor-Mageplaza** [comment]
Hi @cjnewbs 
Since you were unable to respond within the time range, I will close this issue.
If the problem still persists, you can contact us via the support portal.
Thank you.
