### ISSUE TITLE
Hi Sir, Could you add china social login into this extensions?

### ISSUE THREAD

**Issue by mugua** [mageplaza/magento-2-social-login#150]
Hi Sir, Could you add china social login into this extensions? such as, Wechat login, QQ login, Alipay Login, Weibo Login and so on...

**Comment by Victor-Mageplaza** [comment]
Hi @mugua 
I'm Victor from Mageplaza.
First of all, I would like to thank you for your suggestions.
We have been working to improve the Social Login module.
Therefore, your request can completely become a new function in the future.

**Comment by Victor-Mageplaza** [comment]
Hi @mugua 
Since you were unable to respond within the time range, I will close this issue.
If the problem still persists, you can contact us via the support portal.
Thank you.
