### ISSUE TITLE
Pop up doesnt show up when clicked on login/create account.

### ISSUE THREAD

**Issue by Ganesh-1996** [mageplaza/magento-2-social-login#151]
The login popup doesn't show up when clicked on Login/create account.
Environment:
1. Magento 2.3.x
2. Custom theme - Wokiee
Refer the image on how the login page looks like.
![login](https://user-images.githubusercontent.com/40562868/64001003-87da4280-cb24-11e9-9cbb-c3afbe6e10e7.PNG)

**Comment by Victor-Mageplaza** [comment]
Hi @Ganesh-1996 
I'm Victor from Mageplaza. I would like to answer your problem briefly:
- Please check the settings to see if you have enabled the option to use pop-ups?
- Can you log in using the social login buttons?
- If you have the correct settings and can log in normally but the pop-up does not appear, it is likely that our module is not yet compatible with your theme.

**Comment by Ganesh-1996** [comment]
Hi Victor,
Ive enabled the option to use pop-ups. Im also able to login via social login buttons.

**Comment by Victor-Mageplaza** [comment]
Hi @Ganesh-1996 
I think now you should temporarily use the social button and log in at customer/account/login page. We will find a solution that is compatible with your theme in the next version.
If you have problems using or using pop-ups that are part of your site building plan, please contact us via the customer support portal. They will help you. Thank you!

**Comment by Victor-Mageplaza** [comment]
Hi @Ganesh-1996 
Since you were unable to respond within the time range, I will close this issue.
If the problem still persists, you can contact us via the support portal.
Thank you.
