### ISSUE TITLE
It is possible to get the social login buttons on register form popup?

### ISSUE THREAD

**Issue by lucasvm** [mageplaza/magento-2-social-login#154]
Hello

 I would like to know if there is a wat to get the social login block displayed on the register form popup? i can only see it on login popup.

**Comment by Victor-Mageplaza** [comment]
I'm Victor from Mageplaza. I would like to answer your question briefly as follows:
Although there is no option to use Social Buttons for the register form popup but it is possible to add Social Buttons to that popup.

**Comment by lucasvm** [comment]
But how?, is there a block i can call via layout xml or inside the phtml? on witch files?, also i dont see the buttons on this page, customer/account/create/ , well the same, if there is a block to place it could help to know how its calling.

**Comment by Victor-Mageplaza** [comment]
Thanks for your answer. I would like to answer your question, we add social login buttons to login popup using JS you can also do the same with popup create ( refer to the following picture || https://prnt.sc/pc5gcq ). Even more flexible, you can use widgets and you can bring social login buttons wherever you want.

**Comment by Victor-Mageplaza** [comment]
Since there has been no response for a long time, I would like to close the topic here.
If you encounter any problems or have any questions please reopen the topic.
Thank you!
