### ISSUE TITLE
Errors during compilation:         Mageplaza\SocialLogin\Controller\Popup\Create                 Missed required argument customerRepository in parent::__construct call. File: /home/demo4756/stage2/vendor/mageplaza/magento-2-social-login/Controller/Popup/Create.php Total Errors Count: 1

### ISSUE THREAD

**Issue by kriswen** [mageplaza/magento-2-social-login#158]
### Preconditions

1. Magento: Magento 2.3.3
2. PHP: 7.1.3 
3. MySQL: 5.6

### Steps to reproduce

1. disabled social login extension(for magento 2.2), and removed from app/code folder 
1. composer require mageplaza/magento-2-social-login
2. php bin/magento setup:upgrade
3. php bin/magento setup:di:compile

### Expected result
1. successfully compiled

### Actual result
1. [Screenshot, logs]
Errors during compilation:         Mageplaza\SocialLogin\Controller\Popup\Create                 Missed required argument customerRepository in parent::__construct call. File: /home/xxxxx/stage2/vendor/mageplaza/magento-2-social-login/Controller/Popup/Create.php Total Errors Count: 1

**Comment by Victor-Mageplaza** [comment]
I'm Victor from Mageplaza. I would like to answer to your issue.
You can refer to this link: https://github.com/mageplaza/magento-2-social-login/issues/155
This issue we have received and we will make a pull request to fix the error. Thank you!

**Comment by kriswen** [comment]
thank you.
