### ISSUE TITLE
Can't login on my website! Magento 2

### ISSUE THREAD

**Issue by AdrianoFSX** [mageplaza/magento-2-social-login#159]
Hi,
I am trying to login using the extension, but this error always appears

Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Eav\Model\Attribute\Data\Text::validateLength() must be of the type string, null given, called in /srv/public_html/vendor/magento/module-eav/Model/Attribute/Data/Text.php on line 80 and defined in /srv/public_html/vendor/magento/module-eav/Model/Attribute/Data/Text.php:141 Stack trace: #0 /srv/public_html/vendor/magento/module-eav/Model/Attribute/Data/Text.php(80): Magento\Eav\Model\Attribute\Data\Text->validateLength(Object(Magento\Customer\Model\Attribute), NULL) #1 /srv/public_html/vendor/magento/module-eav/Model/Validator/Attribute/Data.php(131): Magento\Eav\Model\Attribute\Data\Text->validateValue(NULL) #2 /srv/public_html/vendor/magento/framework/Validator/Constraint.php(54): Magento\Eav\Model\Validator\Attribute\Data->isValid(Object(Magento\Customer\Model\Customer\Interceptor)) #3 /srv/public_html/vendor/magento/framework/Validator.php(59): Magento\Framework\Validator\Constraint->isValid(Object(Magento\Customer\Model\Customer\Interceptor)) #4 /srv/public in /srv/public_html/vendor/magento/module-eav/Model/Attribute/Data/Text.php on line 141

Both on Facebook and Google

**Comment by gustavoulyssea** [comment]
I have the same issue here for NEW accounts only.

**Comment by cayohenrique** [comment]
Some news about that?

**Comment by cayohenrique** [comment]
Hello, I think I found the solution for this case.
Probably you are trying to put as mandatory some field that the FB and Google API doesn't provide.
In my case was the VAT number. When I change it as "optional", the login worked.
