### ISSUE TITLE
Facebook & Twitter Login REST API

### ISSUE THREAD

**Issue by msliman** [mageplaza/magento-2-social-login#16]
How can I use REST API for login with facebook and twitter?
Please help.

### Preconditions

1. Magento: 2.1.5
2. PHP: 7
3. MySQL: 5.6
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by haitv282** [comment]
Hi there,

We are so sorry, at this moment we didn't support REST API for social login.
Please kindly understand.
