### ISSUE TITLE
Missed required argument error when running setup:di:compile command

### ISSUE THREAD

**Issue by BerndLang** [mageplaza/magento-2-social-login#160]
When running `bin/magento setup:di:compile` the following error message is thrown:

`Errors during compilation:
        Mageplaza\SocialLogin\Controller\Popup\Create
                Missed required argument customerRepository in parent::__construct call. File: /var/www/magento/vendor/mageplaza/magento-2-social-login/Controller/Popup/Create.php
Total Errors Count: 1
`

*Assumption causing this error*:

In Mageplaza\SocialLogin\Controller\Popup\Create the constructor method calls the parent constructor of Magento\Customer\Controller\Account\CreatePost class. Magento 2.3.3 introduced two new parameters $customerRepository and $formKeyValidator in that constructor. At least $customerRepository parameter is missing in the child constructor.

### Preconditions
1. Magento: **2.3.3**
2. PHP: 7.1.33
3. MySQL: 5.7.28

### Steps to reproduce
1. Install Magento 2.3.3
2. Install magento-2-social-login using composer
3. Run bin/magento setup:di:compile in the Magento root directory

### Expected result
1. bin/magento setup:di:compile should finish without any error

### Actual result
1. The following error message is thrown:

`Errors during compilation:
        Mageplaza\SocialLogin\Controller\Popup\Create
                Missed required argument customerRepository in parent::__construct call. File: /var/www/magento/vendor/mageplaza/magento-2-social-login/Controller/Popup/Create.php
Total Errors Count: 1`

**Comment by BrM123** [comment]
I also have same problem, I am install Mageplaza_SocialLogin on Magento 2.3.3 PHP 7.2.24

I have compile error: https://github.com/mageplaza/magento-2-social-login/issues/155
I made your fix: https://github.com/mageplaza/magento-2-social-login/issues/155#issuecomment-540337991
The compilation was a success. Backend works but frontend does not work. Shows the following error:

{"0":"The \"form_additional_info\" is not a child of \"social-login-popup-create\". Resolve the issue and try again.","1":"<pre>#1 Magento\\Framework\\Data\\Structure->reorderToSibling() called at [vendor\/magento\/framework\/View\/Layout\/Data\/Structure.php:132]\n#2 Magento\\Framework\\View\\Layout\\Data\\Structure->reorderChildElement() called at [vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php:176]\n#3 Magento\\Framework\\View\\Layout\\GeneratorPool->reorderElements() called at [vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php:120]\n#4 Magento\\Framework\\View\\Layout\\GeneratorPool->buildStructure() called at [vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php:79]\n#5 Magento\\Framework\\View\\Layout\\GeneratorPool->process() called at [vendor\/magento\/framework\/View\/Layout.php:343]\n#6 Magento\\Framework\\View\\Layout->generateElements() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:89]\n#7 Magento\\Framework\\View\\Layout\\Interceptor->generateElements() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:129]\n#8 Magento\\Framework\\View\\Layout\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Page\/Builder.php:55]\n#9 Magento\\Framework\\View\\Page\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:65]\n#10 Magento\\Framework\\View\\Layout\\Builder->build() called at [vendor\/magento\/framework\/View\/Layout.php:253]\n#11 Magento\\Framework\\View\\Layout->build() called at [vendor\/magento\/framework\/View\/Layout.php:875]\n#12 Magento\\Framework\\View\\Layout->getBlock() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:414]\n#13 Magento\\Framework\\View\\Layout\\Interceptor->getBlock() called at [vendor\/magento\/module-cms\/Helper\/Page.php:171]\n#14 Magento\\Cms\\Helper\\Page->prepareResultPage() called at [vendor\/magento\/module-cms\/Controller\/Index\/Index.php:74]\n#15 Magento\\Cms\\Controller\\Index\\Index->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#16 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#17 Magento\\Cms\\Controller\\Index\\Index\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#18 Magento\\Cms\\Controller\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#19 Magento\\Cms\\Controller\\Index\\Index\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Cms\/Controller\/Index\/Index\/Interceptor.php:26]\n#20 Magento\\Cms\\Controller\\Index\\Index\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#21 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#22 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#23 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#24 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php:94]\n#25 Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#26 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:69]\n#27 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#28 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#29 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#30 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:137]\n#31 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#32 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#33 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n<\/pre>","url":"\/","script_name":"\/index.php"}

**Comment by BerndLang** [comment]
The fix https://github.com/mageplaza/magento-2-social-login/issues/155#issuecomment-540337991 works for our installation. Backend and Frontend works fine. Social Login Popup shows up with no error.
