### ISSUE TITLE
Facebook login fails and redirects to login page.

### ISSUE THREAD

**Issue by BezV8** [mageplaza/magento-2-social-login#162]
Looks related to #159. When attempting to login via facebook on the site it fails with no error message a redirects back to the login page.
 

### Preconditions

1. Magento: 2.2.1
2. Social Login: 2.7.5

### Steps to reproduce

1. Go to login page. /customer/account/login/
2. Click 'Sign in with Facebook'
3. Accept any popup dialogs.

### Expected result

1. Customer is logged in.

### Actual result

1. Page refreshed without signing customer in. No error messages are printed.

**Comment by snoroozi** [comment]
Same. That's why I've always used the weltpixel version. But now I'm using infinit theme and this module comes integrated so thought i'd give another shot. Same issues again.  Somehow related to how it interacts with varnish i think.

**Comment by iocampomx** [comment]
I have the same issue, I disabled Varnish and the problem persists. I saw the latest version that was updated today (May 4th) but even with that, isn't working. Thanks!

**Comment by onevn** [comment]
$requiredMoreInfo = (int) $this->apiHelper->requiredMoreInfo();
            if ((!$userProfile->email && $requiredMoreInfo === 2) || $requiredMoreInfo === 1) {
                $this->session->setUserProfile($userProfile);

                return $this->_appendJs(sprintf(
                    "<script>window.close();window.opener.fakeEmailCallback('%s','%s','%s');</script>",
                    $type,
                    $userProfile->firstName,
                    $userProfile->lastName
                ));
            }
            $customer = $this->createCustomerProcess($userProfile, $type);//This is wrong ;)
-----------
Should change to:
            $requiredMoreInfo = (int) $this->apiHelper->requiredMoreInfo();
            if ((!$userProfile->email && $requiredMoreInfo === 2) || $requiredMoreInfo === 1) {
                $this->createCustomerProcess($userProfile, $type);
                $this->session->setUserProfile($userProfile);

                return $this->_appendJs(sprintf(
                    "<script>window.close();window.opener.fakeEmailCallback('%s','%s','%s');</script>",
                    $type,
                    $userProfile->firstName,
                    $userProfile->lastName
                ));
            }
            $customer = $this->apiObject->getCustomerBySocial($userProfile->identifier, $type);
Will solve your problem :)

**Comment by Victor-Mageplaza** [comment]
I'm Victor from Mageplaza. I would like to answer your question.
First of all I'd like to thank @onevn  found and fixed the problem.
Then I have a small question like this: Do any of you have the same problem with other providers Facebook?
Thanks!

**Comment by Victor-Mageplaza** [comment]
Due has passed a period of no response. I will close this topic here.
If you have the same problem, do not hesitate to reopen the topic.
Thank you!
