### ISSUE TITLE
CustomerData customer logic reload not completed before redirect

### ISSUE THREAD

**Issue by exequielserfe** [mageplaza/magento-2-social-login#164]
Sometimes when customer uses the Facebook login they are not logged successfully.

### Preconditions 
1. Magento: 2.2.8
2. PHP: 7.1

### Steps to reproduce
1. Login with Facebook account

### Expected result
1. Customer being logged

### Actual result
1. Customer is not logged

I debugged and confirmed that the problem is caused by the reload or redirect action being executed before the customerData "customer" reload is completed. 

When our server response takes too long, the page is reloaded before the customer data is completed updated. This happens here: view/frontend/web/js/provider.js

`customerData.reload(['customer'], true)
`
Which is executed asynchronously, I moved the reload logic into the done() execution and it fixed the problem

```
window.socialCallback = function (url, windowObj) {
        customerData.invalidate(['customer']);
        customerData.reload(['customer'], true).done(function() {
           if (url !== '') {
               window.location.href = url;
           } else {
               window.location.reload(true);
           }
           windowObj.close();
        });
    };
```

**Comment by exequielserfe** [comment]
I created this pull request with the fix I implemented in our site

https://github.com/mageplaza/magento-2-social-login/pull/165

**Comment by Victor-Mageplaza** [comment]
I'm Victor from Mageplaza.
Thank you so much for the pull request. I will check and let you know.
Also, maybe your issue related to #162 you should take a look at that thread.
Thank you!
