### ISSUE TITLE
How to disable the pop up ?

### ISSUE THREAD

**Issue by msliman** [mageplaza/magento-2-social-login#17]
How to disable the popup window? 
All configuration in backend force to use popup !!

**Comment by haitv282** [comment]
Hi there,

In current version, we didn't support the disable popup window feature. If you want to disable it, you can open file `app\code\Mageplaza\SocialLogin\view\frontend\templates\popup.phtml` and change line 17 line this:
`<?php if ($block->isEnabled()): ?>` => `<?php if (false): ?>`

We will note and improve this feature in the next update. Thank you very much.
