### ISSUE TITLE
 Column not found: 1054 Unknown column 'status' in 'where clause'

### ISSUE THREAD

**Issue by raheelsiddiqui** [mageplaza/magento-2-social-login#170]
I have setup the Social Login module with google account. When I try to login, popup appears with my google accounts listed, when I chose one, it gives me the following error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause', query was: SELECT `main_table`.* FROM `mageplaza_social_customer` AS `main_table` WHERE (`social_id` = '115950745749932023169') AND (`type` = 'Google') AND (`status` IS NULL)

I checked the database, status column is missing. My Magento version is 2.3.3 and Mageplaza Social Login version is 2.8.0

Would be great if someone helps me here.

Thanks

**Comment by hsriar** [comment]
Create a Column with name "**status**" in **mageplaza_social_customer** table

**Comment by hsriar** [comment]
Create a Column with name "**status**" in **mageplaza_social_customer** table

**Comment by Victor-Mageplaza** [comment]
Hi @raheelsiddiqui ,
I'm Victor from Mageplaza. I would like to answer your question as follow.
It was an error when executing code from the dev branch to the master branch.
Here is the patch to fix this error, please download this replace into the module and run setup deploy commands to take effect:
https://drive.google.com/file/d/1CH22Q1s-MS-zhvrRzz3rowED3De6lK7w/view?usp=sharing
Thank you!

**Comment by raheelsiddiqui** [comment]
> Hi @raheelsiddiqui ,
> I'm Victor from Mageplaza. I would like to answer your question as follow.
> It was an error when executing code from the dev branch to the master branch.
> Here is the patch to fix this error, please download this replace into the module and run setup deploy commands to take effect:
> https://drive.google.com/file/d/1CH22Q1s-MS-zhvrRzz3rowED3De6lK7w/view?usp=sharing
> Thank you!

Thank you, would you please let me know the steps to apply this patch. Please note I am not very technical.

**Comment by raumatbel** [comment]
Hi @Victor-Mageplaza ,
I have the same error, but my installation was done by composer. When do you think you will have it to update the module by composer?

**Comment by hunterallen** [comment]
> Create a Column with name "**status**" in **mageplaza_social_customer** table

I can confirm this works. 

`alter table mageplaza_social_customer add status VARCHAR( 255 ) after social_created_at;`

**Comment by joaolisboa** [comment]
ETA to add column in the actual UpgradeSchema? No one should have to manually create the column or install a patch for an error like this, specially after 2 months.

**Comment by joaolisboa** [comment]
@Victor-Mageplaza Can you reopen and fix this issue in the actual module? None of these are actual solutions, because creating the column manually or adding a patch is not the way to go.

**Comment by zzvara** [comment]
This is still an issue, and the plugin does not work with Magento 2.3.4.

**Comment by joaolisboa** [comment]
@zzvara Due to this issue the plugin won't work on any Magento version at all the moment you upgrade to latest version because of the missing column creation.

**Comment by zzvara** [comment]
@joaolisboa are you saying that it would not work with 2.3.4, is that correct? My 2.3.4 is a fresh installation, not an upgrade.

**Comment by joaolisboa** [comment]
@zzvara Doesn't matter, the way it currently it is it won't work on any version of Magento, whether you upgraded or not. You'll have to use one of the workarounds or wait until they patch the column creation

**Comment by zzvara** [comment]
So the workaround is to manually conduct the following statement in the DB?

`alter table mageplaza_social_customer add status VARCHAR( 255 ) after social_created_at;`

**Comment by nived** [comment]
@zzvara it is working,  after adding the field manually.

**Comment by joaolisboa** [comment]
@zzvara as mentioned above that workaround fixes it, of course, since that's the missing column in the database. My issue is not with the workaround but the fact that such an obvious workaround is needed. Looks like a PR has been created but an actual fix is still not available. It's been 3 months now without an actual fix. @imsamthomas @Victor-Mageplaza How long until the fixed is released?

**Comment by zzvara** [comment]
I can confirm that:

`alter table mageplaza_social_customer add status VARCHAR( 255 ) after social_created_at;`

works.

**Comment by kazimnoorani8704** [comment]
Make changes in 2 files.
1. **app/code/Mageplaza/SocialLogin/etc/module.xml**
Line Number 24 : `<module name="Mageplaza_SocialLogin" setup_version="1.1.1">`

2. **app/code/Mageplaza/SocialLogin/Setup/UpgradeSchema.php**
Add below code after line number 56
`if (version_compare($context->getVersion(), '1.1.1', '<')
            && $connection->tableColumnExists($tableName, 'status') === false
        ) {
            $connection->addColumn(
                $tableName,
                'status',
                [
                    'type'    => Table::TYPE_TEXT,
                    'length' => 255,
                    'comment' => 'Status',
                ]
            );
        }`

It works for me. Thought to share using UpgradeSchema.php .
