### ISSUE TITLE
Social Login on Magento 2.3.3 -->  Fatal error: Uncaught Error: Call to a member function isRequireMoreInfo() on boolean...

### ISSUE THREAD

**Issue by harshbharucha** [mageplaza/magento-2-social-login#173]
### **Issue Summary:**

Error on enabling Social Login with Google login

Sign in with Google

Fatal error: Uncaught Error: Call to a member function isRequireMoreInfo() on boolean in /var/www/html/techshirts.in/public_html/vendor/mageplaza/magento-2-social-login/view/frontend/templates/form/social.phtml:41 Stack trace: #0 /var/www/html/techshirts.in/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include() #1 /var/www/html/techshirts.in/public_html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Mageplaza\SocialLogin\Block\Popup\Social), '/var/www/html/t...', Array) #2 /var/www/html/techshirts.in/public_html/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/var/www/html/t...') #3 /var/www/html/techshirts.in/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1097): Magento\Framework\View\Element\Template->_toHtml() #4 /var/www/html/techshirts.in/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1101): Magento\Framework\View\Element\Abs in /var/www/html/techshirts.in/public_html/vendor/mageplaza/magento-2-social-login/view/frontend/templates/form/social.phtml on line 41

### **Environment**

1. Magento 2.3.3
2. PHP 7.1.33
3. MySQL: 10.0.38-MariaDB
4. Ubuntu 16.04 LTS

### Steps to reproduce

1. Install Magento 2.3.3 on LAMP stack as above (I suspect different LAMP stack would also have same issue)
2. Remove Mageplaza Core and Social login that comes pre-installed with Magento 2.3,3. The reason for this is that while installing other Mageplaza extensions, we get conflict due to multiple Mageplaza cores. See This issue: https://github.com/mageplaza/module-core/issues/3
3. Install Mageplaza SMTP (with core module) using composer. (using this guide: https://docs.mageplaza.com/social-login-m2/install.html) Enable the extension, clear static content, and do the upgrade-compile-deploy sequence.
4. Enable the extension from Store > Configuration > Mageplaza Extensions. Setup Google Login using Google's Domains API.

### Expected result
 
1. Extension should be enabled and Google login functionality should be enabled

### Actual result
Error on Website Fronted. Website Backend Working Fine.
This is the error (same as pasted in Issue summary):

Sign in with Google

Fatal error: Uncaught Error: Call to a member function isRequireMoreInfo() on boolean in /var/www/html/techshirts.in/public_html/vendor/mageplaza/magento-2-social-login/view/frontend/templates/form/social.phtml:41 Stack trace: #0 /var/www/html/techshirts.in/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include() #1 /var/www/html/techshirts.in/public_html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Mageplaza\SocialLogin\Block\Popup\Social), '/var/www/html/t...', Array) #2 /var/www/html/techshirts.in/public_html/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/var/www/html/t...') #3 /var/www/html/techshirts.in/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1097): Magento\Framework\View\Element\Template->_toHtml() #4 /var/www/html/techshirts.in/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1101): Magento\Framework\View\Element\Abs in /var/www/html/techshirts.in/public_html/vendor/mageplaza/magento-2-social-login/view/frontend/templates/form/social.phtml on line 41

**Comment by chavesfop** [comment]
Same issue here, with Magento 2.2.3

**Comment by infinityredux** [comment]
Looking at that error, seems that it's failing to actually obtain the controller object, with a boolean (probably `false`) being returned instead.

I've been having another error when attempting to run through DI compliation. Educated guess... because Magento can't compile the dependency injection, it can't obtain a valid object, hence returning an error value instead.

Exact error I'm getting:
```
Errors during compilation:
        Mageplaza\SocialLogin\Controller\Popup\Create
                Missed required argument customerRepository in parent::__construct call. File: /var/www/vhosts/casewine.co.uk/httpdocs/vendor/mageplaza/magento-2-social-login/Controller/Popup/Create.php
Total Errors Count: 1
```

Seems like whatever the controller is extending got an extra contructor argument in the latest release.

**Comment by ansarul121** [comment]
Hi i am also facing same issue 

Fatal error: Uncaught Error: Call to a member function isRequireMoreInfo() on boolean in /home/doorstep/public_html/holland/app/code/Mageplaza/SocialLogin/view/frontend/templates/form/social.phtml:41 Stack trace: #0 /home/doorstep/public_html/holland/vendor/magento/framework/View/TemplateEngine/Php.php(59): include() #1 /home/doorstep/public_html/holland/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Mageplaza\SocialLogin\Block\Popup\Social), '/home/doorstep/...', Array) #2 /home/doorstep/public_html/holland/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/home/doorstep/...') #3 /home/doorstep/public_html/holland/vendor/magento/framework/View/Element/AbstractBlock.php(668): Magento\Framework\View\Element\Template->_toHtml() #4 /home/doorstep/public_html/holland/vendor/magento/framework/View/Element/AbstractBlock.php(559): Magento\Framework\View\Element\AbstractBlock->toHtml() #5 [internal functio in /home/doorstep/public_html/holland/app/code/Mageplaza/SocialLogin/view/frontend/templates/form/social.phtml on line 41

**Comment by Victor-Mageplaza** [comment]
Pull request #191
