### ISSUE TITLE
guest Customer Data not passed M2.2.9

### ISSUE THREAD

**Issue by primisuimotori** [mageplaza/magento-2-social-login#178]
guest Customer Data not passed from create account button at the end of checkout and customer/account/create page
 
1. Magento: 2.2.9
2. PHP: 7.1.2

**Comment by Victor-Mageplaza** [comment]
I'm Victor from Mageplaza.
Can you let me know more details about your issue?
Thank you!

**Comment by Victor-Mageplaza** [comment]
Due has passed a period of no response. I will close this topic here.
If you have the same problem, do not hesitate to reopen the topic.
Thank you!
