### ISSUE TITLE
"Sign In" not translated

### ISSUE THREAD

**Issue by mageho** [mageplaza/magento-2-social-login#182]
Good afternoon,
 
I would like to notice you about this line : 
https://github.com/mageplaza/magento-2-social-login/blob/0bfc44b93e1e1d34d4c1ee60cb46dc11a34a0470/view/frontend/web/js/view/authentication.js#L56

No translation is operated by knockout because it is already processed before the JS replacement.

You need to use $t

**Comment by mageho** [comment]
`'        <span>' + $t('Sign In') + '</span>\n' + `

**Comment by Victor-Mageplaza** [comment]
@mageho Thank you so much for your contribution!
I will update it on our module.

**Comment by Userr017** [comment]
Why this fix not added to latest extension version?

**Comment by Userr017** [comment]
> @mageho Thank you so much for your contribution!
> I will update it on our module.

Why this fix not added to latest extension version? `' <span>' + $t('Sign In') + '</span>\n' +`

**Comment by mageho** [comment]
This issue is still open !
