### ISSUE TITLE
IE11 JS Problems (add to cart)

### ISSUE THREAD

**Issue by EFvS** [mageplaza/magento-2-social-login#184]
**mageplaza/magento-2-social-login** breaks the add-to-cart button in IE11 

### Preconditions

1. Magento: 2.2
2. PHP: 7.1
3. MySQL: 5.6
4. Browser: IE11

### Steps to reproduce

1. Go to a Product Detail Page
2. Add to cart

### Expected result

1. Product added to cart

### Actual result

1. Product is not added and we get an error in the console
<img width="586" alt="Bildschirmfoto 2020-04-20 um 18 40 14" src="https://user-images.githubusercontent.com/10548328/79776768-7f927a00-8336-11ea-9f35-0c48924a490b.png">

``SCRIPT5007: Unable to get property 'sectionLoadUrl' of undefined or null reference``

### Suggested Solution
The problem is in `Mageplaza/SocialLogin/view/frontend/web/js/popup.js`
IE 11 can't handle the javascript function "includes".
So if the function "includes" is replaced with "indexOf", IE11 will work again

**Comment by Victor-Mageplaza** [comment]
Hi @EFvS,
Exactly! It's undeniable that the current spelling of the module is not optimal.
Thanks so much for your contributions!
