### ISSUE TITLE
Send Password to Customer not send any email after login

### ISSUE THREAD

**Issue by gumilar1995** [mageplaza/magento-2-social-login#189]
After enabling send password to customer nothing email has been sent after login by social media, any step I miss on it?
  

1. Magento: 2.3.3
2. Mageplaza Social Login : 2.8.0
3. Mageplaza SMTP : 1.3.0

**Comment by Victor-Mageplaza** [comment]
I fixed it on the newest version of the SocialLogin module.
You should try the new version and let me know about the result.
Thank you!

**Comment by gumilar1995** [comment]
It solved now, thanks
