### ISSUE TITLE
i have a proplem with social login with mageplaza

### ISSUE THREAD

**Issue by EngPeterMaged** [mageplaza/magento-2-social-login#190]
i have a proplem with social login with mageplaza . 
"Ooophs, we got an error: Facebook Graph returned an error: The URL could not be loaded: The domain of this URL was not included in the application domains. In order to download this URL, please add all of your app’s domains and subdomains to the "Application Domains" field in the app settings."
### Preconditions

1. Magento: 2.3.3
2. PHP: 7.3
3. MySQL: 
4. Codazon theme infinite magento 2
5. Facebook App on Developer console

### Steps to reproduce

1.  configure my Facebook app
2. add app domain and site URL 
3.make my app live 
4.  insert my app configuration into system->configuration ->mage plaza extensions ->Facebook 
5. insert OAuth valid URL as the document
note : in valid Valid OAuth Redirect URI
 URL in setting the URL doesn't contain https but in Facebook app configuration in Facebook developer console must contain a https
6. try to login 

### Expected result

1. 

  

### Actual result

![2020-06-10 (2)](https://user-images.githubusercontent.com/57891823/84245682-b9495b00-ab05-11ea-8d25-44f6389dd5ca.png)
![2020-06-10 (3)](https://user-images.githubusercontent.com/57891823/84245685-bb131e80-ab05-11ea-8a68-d0295b454bc2.png)
![2020-06-10 (4)](https://user-images.githubusercontent.com/57891823/84245688-bc444b80-ab05-11ea-8171-840a3a20ff48.png)
![2020-06-10 (5)](https://user-images.githubusercontent.com/57891823/84245693-bd757880-ab05-11ea-9b4b-2b2a1c22b395.png)
![2020-06-10 (7)](https://user-images.githubusercontent.com/57891823/84245695-bea6a580-ab05-11ea-80aa-a4817a9534fe.png)

**Comment by Victor-Mageplaza** [comment]
You should fill this field with your redirect URL || http://prntscr.com/tf6yeo
Then try again. Thank you!

**Comment by Victor-Mageplaza** [comment]
Due has passed a period of no response. I will close this topic here.
If you have the same problem, do not hesitate to reopen the topic.
Thank you!
