### ISSUE TITLE
Instagram Login Not Working

### ISSUE THREAD

**Issue by ecoprince** [mageplaza/magento-2-social-login#196]
### Preconditions

1. Magento: 2.3.5
2. PHP: 7.2

### Steps to reproduce

1. Click on Sign In With Instagram
2. Enter username and password, login successfully
3. After logged in it's showing blank popup with error "Oops, an error occurred."

**This URL showing response "Oops, an error occurred." with status 500**
https://www.instagram.com/oauth/authorize/?client_id=XXXXXXXXXX&redirect_uri=https%3A%2F%2Fmysite.com%2Fsociallogin%2Fsocial%2Fcallback%2F%3Fhauth.done&response_type=code&scope=basic

![image](https://user-images.githubusercontent.com/65884210/87152073-a4addd80-c2d2-11ea-9576-29267bcf7db9.png)

**This is also in your demo site** but it has different error in your demo: https://social-login-pro.demo2.mageplaza.com/

 {"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope field(s): basic"}

![Screenshot 2020-07-10 at 13 36 02](https://user-images.githubusercontent.com/65884210/87151718-face5100-c2d1-11ea-8c01-d185e05ea0e6.png)

**Comment by Victor-Mageplaza** [comment]
Hi @ecoprince 
I'm Victor from Mageplaza. I would like to answer your question.
The current Instagram API that the module is using is the old API.
Instagram's new login API system in cooperation with Facebook is under development and there is no official announcement yet. I am always updating the latest information from the library that the module uses. I will update the new API as soon as it progresses. For now, you should temporarily turn off Instagram.
Thank you!

**Comment by Victor-Mageplaza** [comment]
Due has passed a period of no response. I will close this topic here.
If you have the same problem, do not hesitate to reopen the topic.
Thank you!

**Comment by VivekShingala** [comment]
> Hi @ecoprince
> I'm Victor from Mageplaza. I would like to answer your question.
> The current Instagram API that the module is using is the old API.
> Instagram's new login API system in cooperation with Facebook is under development and there is no official announcement yet. I am always updating the latest information from the library that the module uses. I will update the new API as soon as it progresses. For now, you should temporarily turn off Instagram.
> Thank you!

What is the good time to turn on Instagram login?
