### ISSUE TITLE
Social login does not display on authentication popup

### ISSUE THREAD

**Issue by GioOsef** [mageplaza/magento-2-social-login#198]
Hi, I just installed the plugin. I have the buttons that appear on the customer/login and customer/create pages but they don't appear on the checkout authentication pop up.

### Preconditions

1. Magento: 2.3.4
2. PHP: 7.2

Here are the login and create pages :
![image](https://user-images.githubusercontent.com/6666002/90773401-1d528180-e2f6-11ea-9f6b-a01c2cda2643.png)
![image](https://user-images.githubusercontent.com/6666002/90773454-35c29c00-e2f6-11ea-87f3-a72b29f7d25a.png)

And this is the authentication pop up : 
![image](https://user-images.githubusercontent.com/6666002/90773551-5c80d280-e2f6-11ea-8bc2-d22550d44b70.png)

The config : 
![image](https://user-images.githubusercontent.com/6666002/90773666-876b2680-e2f6-11ea-9333-6d444e2ef431.png)

**Comment by Victor-Mageplaza** [comment]
Hi @GioOsef 

I'm Victor from Mageplaza. I would like to answer your question.

Chances are that the class structure your theme uses is different from the Magento default theme so your problem just happened. You can customize the "Popup Links Selector" settings to achieve the desired effect.

Please try and let me know. Thank you!

Best Regard,
Victor
