### ISSUE TITLE
Login/Register popup not triggered when user visits the link directly

### ISSUE THREAD

**Issue by lokeshvnaik** [mageplaza/magento-2-social-login#200]
### Preconditions
1. Magento: 2.3.4

### Steps to reproduce
1. Visit any of the below link directly from the browser
<store_url>/customer/account/login
<store_url>/customer/account/create
<store_url>/customer/account/forgotpassword

### Expected result
1. User should be redirected to the home page and trigger the respective popup instead of loading default login, register or forgot password page

### Actual result
1. Magento's default login, register and forgot password page is loaded

Also on certain events Magento creates links as below. So popup should be triggered for such links also.
<store_url>/customer/account/login/referer/aHR0cHM6Ly91YWUuZ2VlcGFzLmNvbS9lbi9jdXN0b21lci9hY2NvdW50L2luZGV4Lw%2C%2C/

**Comment by Victor-Mageplaza** [comment]
Hi @lokeshvnaik 

I'm Victor from Mageplaza.
I tried following your steps but the problem didn't happen on my site.
Can you check it again and let me know?

Thank you!
Best Regards,
Victor

**Comment by Victor-Mageplaza** [comment]
I would like to temporarily close the issue due to no response.
Don't hesitate to reopen the topic if you have problems.
Thank you!
