### ISSUE TITLE
installation fail on social suite for magento 2.2.8

### ISSUE THREAD

**Issue by chungchi300** [mageplaza/magento-2-social-login#209]
### Preconditions

1. Magento: 2.2.8
2. PHP:  7
3. MySQL: 5.6 
4. 

### Steps to reproduce

1. download social suite
2. php bin/magento setup:upgrade
3. php bin/magento setup:static-content:deploy -f
4. php bin/magento cache:flush

### Expected result

1. App installed in pages 

### Actual result

Fatal error: Uncaught Error: Cannot instantiate abstract class Mageplaza\FacebookPlugin\Block\Facebook in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111 Stack trace: #0 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Mageplaza\\Faceb...', Array) #1 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Mageplaza\\Faceb...', Array) #2 /var/www/html/vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Mageplaza\\Faceb...', Array) #3 /var/www/html/vendor/magento/framework/View/Layout/Generator/Block.php(270): Magento\Framework\View\Element\BlockFactory->createBlock('Mageplaza\\Faceb...', Array) #4 /var/www/html/vendor/magento/framework/View/Layout/Generator/Block.php(250): Magento\Framework\View\Layout\Generator\Block->getBlockInst in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111

**Comment by Victor-Mageplaza** [comment]
Hi @chungchi300 

I'm Victor from Mageplaza. I would like to answer your question.
As you can see the error message belongs to the Facebook Plugin module.
You can create an issue at https://github.com/mageplaza/magento-2-facebook-plugin

Best Regards,
Victor
