### ISSUE TITLE
Is it working on the Magneto 2.4.* EE ?

### ISSUE THREAD

**Issue by karangar** [mageplaza/magento-2-social-login#211]
### Preconditions

1. Magento: magento 2.4.*

### Steps to reproduce

1. When i trying to login with Google and Facebook
2. It's every time asking firstname, Lastname, email and password

### Expected result

1. If account not then create the account other wise it will Login. 

### Actual result

1. When i login It's every time asking firstname, Lastname, email and password

**Comment by Victor-Mageplaza** [comment]
I'm Victor from Mageplaza. I would like to answer your question.

Due to Magento's demand for security from the Marketplace, currently, the module's default thread will require the customer to confirm their identity before entering.
You can disable this constraint at the module settings.

Thank you!

Best Regards,
Victor

**Comment by karangar** [comment]
But it's asking me every time

**Comment by karangar** [comment]
![screenshot-2020 11 24-12_16_20](https://user-images.githubusercontent.com/34768419/100058426-3f0c5900-2e4f-11eb-9a62-b7e6d26a370b.png)
Please check above configuration setting

**Comment by Victor-Mageplaza** [comment]
Please temporarily turn off using the login popup and try again with the Social login buttons at the login page.
Then let me know about the result.
Thank you!

Best Regards,
Victor

**Comment by karangar** [comment]
Hello Team,

Yes, I have disable login popup. And try with a login page, but There login is not working just close the Google and Facebook PopUp Nothing happen like a login.

Can you please Confirm is it work or not from Your side? Because it doesn't work from my side.
