### ISSUE TITLE
Social login NOT working on mobiles

### ISSUE THREAD

**Issue by axellelarios** [mageplaza/magento-2-social-login#213]
Hello,

I'm trying the social login module but I'm having lot of issues.

On mobile (im using samsung s9), all login are not working and it stays on a blank page.

This happen even for the demo social login
https://social-login-pro.demo2.mageplaza.com/customer/account/create/

It's not working at all on mobile. What is the issue ?

**Comment by Victor-Mageplaza** [comment]
Hi @axellelarios 

I'm Victor from Mageplaza. I would like to answer your question.
What browser are you using on your phone?
I tried with Chrome on my Xiaomi and found everything still working.
Can you try again and let me know?

Thank you!
Best Regards,
Victor

**Comment by axellelarios** [comment]
Hello Victor,

I have a samsumg S9 and using chrome.

Basically once I click on any social network button it open this window  and its blank with this url https://social-login-pro.demo2.mageplaza.com/sociallogin/social/login/type/facebook/#_=_

Also, I tried it on my magento 2.4, and once people log in with facebook/google on desktop it works and redirect on their account page but when they try to log in again with it it doesn't work anymore. It open a window and then close it.



[Image]



Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by Denda69** [comment]
Hello,
Login popup does not work on mobile when Allow Guest Checkout is set to "No", I haven't worked with magento for many years so debugg seem difficult to me :D,
