### ISSUE TITLE
FACEBOOK NOT NOW get 500error

### ISSUE THREAD

**Issue by slionx** [mageplaza/magento-2-social-login#215]
### Preconditions

1. Magento: 2.3.4
2. PHP: 7.2
How should i fix it?
### Steps to reproduce

1. [
![image](https://user-images.githubusercontent.com/12606252/101115264-0114ef00-361e-11eb-8dbc-2a4f93195b54.png)
](url)
2. Exception #0 (Exception): Could not authorize user, reason: Permissions error (200)
<pre>#1 Hybrid_Auth->__construct() called at [vendor/mageplaza/magento-2-social-login/Model/Social.php:310]
#2 Mageplaza\SocialLogin\Model\Social->getUserProfile() called at [app/code/Silk/SocialLogin/Controller/Social/Login.php:51]
#3 Silk\SocialLogin\Controller\Social\Login->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#4 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
</pre>
3. vendor/hybridauth/hybridauth/hybridauth/Hybrid/Providers/Facebook.php
<pre>
function loginFinish() {
        $helper = $this->api->getRedirectLoginHelper();
        if (isset($_GET['state'])) {
          $helper->getPersistentDataHandler()->set('state', $_GET['state']);
        }
        try {
            $accessToken = $helper->getAccessToken($this->params['login_done']);
        } catch (Facebook\Exceptions\FacebookResponseException $e) {
            throw new Hybrid_Exception('Facebook Graph returned an error: ' . $e->getMessage());
        } catch (Facebook\Exceptions\FacebookSDKException $e) {
            throw new Hybrid_Exception('Facebook SDK returned an error: ' . $e->getMessage());
        }

        if (!isset($accessToken)) {
            if ($helper->getError()) {
                throw new Hybrid_Exception(sprintf("Could not authorize user, reason: %s (%d)", $helper->getErrorDescription(), $helper->getErrorCode()));
            } else {
                throw new Hybrid_Exception("Could not authorize user. Bad request");
            }
        }
</pre>

### Expected result

1. let it pass

**Comment by Victor-Mageplaza** [comment]
Hi @slionx 

I'm Victor from Mageplaza. I would like to answer your question.
You can refer to this image || http://prntscr.com/vvjeo4
In the previous version, I have checked that state but maybe in the new version of FB API, param would be changed.

Thank you!
Best Regards,
Victor

**Comment by slionx** [comment]
@Victor-Mageplaza  Thanks,I fixed it

**Comment by deepaknair3** [comment]
This should be fixed in the extension as well, you should not have closed this.
