### ISSUE TITLE
After Login Succesfully Check Customer Account Not Found

### ISSUE THREAD

**Issue by sfsf7ob** [mageplaza/magento-2-social-login#216]
### Preconditions

1. Magento: 2.3.5-p1
2. PHP: 7.2
3. MySQL: 
4. 

### Steps to reproduce

1. Customer sign-up using social login
2. after create order and try login again
3. account not found

### Expected result

1. after sign up using social login account should saved

### Actual result

1. Customer account not saved.

**Comment by Victor-Mageplaza** [comment]
Hi @sfsf7ob 

I'm Victor from Mageplaza.
I do not see the results you posted. Can you complete the form above?
Thank you!

Best Regards,
Victor

**Comment by sfsf7ob** [comment]
> Hi @sfsf7ob
> 
> I'm Victor from Mageplaza.
> I do not see the results you posted. Can you complete the form above?
> Thank you!
> 
> Best Regards,
> Victor
hello Victor.
I have edit data.

**Comment by Victor-Mageplaza** [comment]
Hi @sfsf7ob 

Yes, I got it.
I have tried on my local site Magento: 2.3.5-p1 with PHP: 7.2 and the module working normally.
Can you let me know your front site then I can go to and check your issue?
Thank you!

Best Regards,
Victor

**Comment by sfsf7ob** [comment]
this is my site 

> Hi @sfsf7ob
> 
> Yes, I got it.
> I have tried on my local site Magento: 2.3.5-p1 with PHP: 7.2 and the module working normally.
> Can you let me know your front site then I can go to and check your issue?
> Thank you!
> 
> Best Regards,
> Victor
https://roastinghouse.sa

**Comment by Victor-Mageplaza** [comment]
Hi @sfsf7ob 

I have logged in to your site successfully. || http://prntscr.com/vxb11v
Can you check my account has been created on your site already?
Thank you!

Best Regards,
Victor

**Comment by sfsf7ob** [comment]
yes i found your account . do you sign-up using google or facebook. i have issue in facebook
![image](https://user-images.githubusercontent.com/45846318/101326886-f7d68d00-387e-11eb-98db-36b67f5857b1.png)

**Comment by Victor-Mageplaza** [comment]
Hi @sfsf7ob 

Yes, your Facebook app has an issue with the config.
Let's check it again and correct it.
You should turn on your app instead of keeping it on developing mode 
Thank you!

Best Regards,
Victor

**Comment by Victor-Mageplaza** [comment]
I would like to temporarily close the issue due to no response.
Don't hesitate to reopen the topic if you have problems.
Thank you!

Best Regards,
Victor
