### ISSUE TITLE
Social Login Extension Error

### ISSUE THREAD

**Issue by krishnaram** [mageplaza/magento-2-social-login#217]
### Preconditions

1. Magento: 2.3.4
2. PHP:  7.2.24
3. MySQL: 14.14

### Steps to reproduce

1.  Installed claue theme. As it already had social login extension Had to to delete folder core and socialLogin from /var/www/html/app/code/Mageplaza/SocialLogin
2. After I set default theme claue. I am getting below exception

### Expected result

1. It should show correct home page without error.

### Actual result

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The "form_additional_info" is not a child of "social-login-popup-create". Resolve the issue and try again.

Exception #0 (Magento\Framework\Exception\LocalizedException): The "form_additional_info" is not a child of "social-login-popup-create". Resolve the issue and try again.
<pre>#1 Magento\Framework\Data\Structure->reorderToSibling('social-login-pop...', 'form_additional_...', 'create-msp-recap...', 1) called at [vendor/magento/framework/View/Layout/Data/Structure.php:132]
#2 Magento\Framework\View\Layout\Data\Structure->reorderChildElement('social-login-pop...', 'form_additional_...', '-', true) called at [vendor/magento/framework/View/Layout/GeneratorPool.php:176]
#3 Magento\Framework\View\Layout\GeneratorPool->reorderElements(&Magento\Framework\View\Layout\ScheduledStructure#000000003a04091200000000111ca024#, &Magento\Framework\View\Layout\Data\Structure#000000003a040f3100000000111ca024#, 'form_additional_...') called at [vendor/magento/framework/View/Layout/GeneratorPool.php:120]
#4 Magento\Framework\View\Layout\GeneratorPool->buildStructure(&Magento\Framework\View\Layout\ScheduledStructure#000000003a04091200000000111ca024#, &Magento\Framework\View\Layout\Data\Structure#000000003a040f3100000000111ca024#) called at [vendor/magento/framework/View/Layout/GeneratorPool.php:79]
#5 Magento\Framework\View\Layout\GeneratorPool->process(&Magento\Framework\View\Layout\Reader\Context#000000003a04090800000000111ca024#, &Magento\Framework\View\Layout\Generator\Context#000000003a04092900000000111ca024#) called at [vendor/magento/framework/View/Layout.php:350]
#6 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:89]
#7 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#8 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:55]
#9 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#10 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:257]
#11 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:882]
#12 Magento\Framework\View\Layout->getBlock('page_content_hea...') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:414]
#13 Magento\Framework\View\Layout\Interceptor->getBlock('page_content_hea...') called at [vendor/magento/module-cms/Helper/Page.php:215]
#14 Magento\Cms\Helper\Page->prepareResultPage(&Magento\Cms\Controller\Index\Index\Interceptor#000000003a040e6900000000111ca024#, 'home') called at [vendor/magento/module-cms/Controller/Index/Index.php:74]
#15 Magento\Cms\Controller\Index\Index->execute(NULL) called at [generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php:24]
#16 Magento\Cms\Controller\Index\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#17 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#18 Magento\Cms\Controller\Index\Index\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#19 Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#20 Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'), array('ajaxcart-action-...'))) called at [generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php:39]
#21 Magento\Cms\Controller\Index\Index\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#) called at [vendor/magento/framework/App/FrontController.php:159]
#22 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#, &Magento\Cms\Controller\Index\Index\Interceptor#000000003a040e6900000000111ca024#) called at [vendor/magento/framework/App/FrontController.php:99]
#23 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#24 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#25 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#26 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#000000003a040c4000000000111ca024#, &Closure#000000003a040c2000000000111ca024#, &Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#27 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#28 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#000000003a040c4000000000111ca024#, &Closure#000000003a040c2000000000111ca024#, &Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#29 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#30 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#31 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000003a040dee00000000111ca024#) called at [vendor/magento/framework/App/Http.php:116]
#32 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#33 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#34 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000003a040d9800000000111ca024#) called at [index.php:39]
</pre>

**Comment by Victor-Mageplaza** [comment]
Hi @krishnaram 

I'm Victor from Mageplaza. I would like to answer your question.
You should delete **Mageplaza_SocialLogin** in the **app/design** folder and then try to re-deploy your site to make this change take effect.
After that, please check it again and let me know about the result.
Thank you!

Best Regards,
Victor

**Comment by krishnaram** [comment]
Hi Victor I dont find this folder in app/design. I have installed magento as well as socialLogin plugin using composer

**Comment by Victor-Mageplaza** [comment]
Hi @krishnaram 

You use the MGS theme, right?
Thank you!

Best Regards,
Victor

**Comment by krishnaram** [comment]
Yes MGS Claue theme

**Comment by Victor-Mageplaza** [comment]
Hi @krishnaram 

Then you go to **app/desgin/MGS/claue** to find **Mageplaza_SocialLogin** folder and delete it. ( I don't remember exactly the path but I know you can find it with my suggestion)
After that please try to re-deploy your site to make this change take effect.

Best Regards,
Victor

**Comment by krishnaram** [comment]
Thanks Victor it has solved the issue. But there is some problem occuring in Social plugin Login

**Comment by Victor-Mageplaza** [comment]
I would like to temporarily close the issue due to no response.
Don't hesitate to reopen the topic if you have problems.
Thank you!

Best Regards,
Victor
