### ISSUE TITLE
Modules requires

### ISSUE THREAD

**Issue by alexvais** [mageplaza/magento-2-social-login#218]
Hi,

Why this module require SMTP, Two Factors and Google recaptcha from mageplaza? why are them mandatory?

**Comment by Victor-Mageplaza** [comment]
Hi @alexvais 

I'm Victor from Mageplaza. I would like to answer your question.

They are declared in the composer.json file.
So when you use composer to install it, it will default to drag the above modules.
Initially, the idea was to provide you with the most complete solution following the main module and supplementary modules.

I apologize if it causes any inconvenience.
Thank you!

Best Regards,
Victor

**Comment by alexvais** [comment]
So this module do not depend of the others? can i remove them?

**Comment by nocturnalfrog** [comment]
@Victor-Mageplaza 

I think it's very bad practice to require modules in your composer file that are optional.
I would like to urge you to remove them from the composer.json file!

If I want to install an SMTP module, I will do so, separately, from a source of my choosing. 

Or as is the actual case for the current project I'm working on; it already has an SMTP module installed. 
Best case I'm going to have to deal with the additional bloat of an unused module but I might very well be looking at resolving module conflicts, backend user confusion, etc.

**Comment by alexvais** [comment]
Also delete from module.xml dependecies, because the modules are not related.

**Comment by KhietNguyen83** [comment]
Thank you for your contributions.
We have fixed the problem in the latest version.
Now when you install the new version, you won't have this problem anymore.
Thank you very much!
