### ISSUE TITLE
Event customer_register_success

### ISSUE THREAD

**Issue by alexvais** [mageplaza/magento-2-social-login#219]
This module do not fire customer_register_success

**Comment by Victor-Mageplaza** [comment]
Hi @alexvais 

You can refer to #177 
Thank you!

Best Regards,
Victor

**Comment by alexvais** [comment]
I mean this event is fire on CreatePost.php when you create a new customer

            $this->_eventManager->dispatch(
                'customer_register_success',
                ['account_controller' => $this, 'customer' => $customer]
            );

this event is not fire when you create a new customer with this module throught social.

Should we add this event on "createCustomerSocial" method ?

**Comment by Victor-Mageplaza** [comment]
It is true that login with Social Network is missing fire **event customer_register_success**.
Compared to Magento's handlers, you can fire that event after creating your Social account.
Thank you!

Best Regards,
Victor

**Comment by Victor-Mageplaza** [comment]
I would like to temporarily close the issue due to no response.
Don't hesitate to reopen the topic if you have problems.
Thank you!

Best Regards,
Victor
