### ISSUE TITLE
Yahoo social login not working as it is deprecated in hybridauth library

### ISSUE THREAD

**Issue by satishgumudavelli** [mageplaza/magento-2-social-login#221]
### Preconditions

1. Magento: Magento 2.3.5
2. PHP: 7.2
3. MySQL: 5.7

### Steps to reproduce

1. Just create client id and client secret for yahoo and test it

### Expected result

1. Unable to auto login

**Comment by Victor-Mageplaza** [comment]
Hi @mageseller
I'm Victor from Mageplaza. I would like to answer your question.
Yes, the library the module uses is being maintained. Changes to Yahoo will be updated in the next version
Thank you!

Best Regards,
Victor

**Comment by mageseller** [comment]
Hi @Victor-Mageplaza,
I have added pull request.
please check should it be useful : 
https://github.com/mageplaza/magento-2-social-login/pull/222

I have added Yahoo Wrapper with new API fixes.

Best Regards,
Satish
