### ISSUE TITLE
Instagram social login is not working, it shows invalid redirect_uri error

### ISSUE THREAD

**Issue by MohitRane** [mageplaza/magento-2-social-login#223]
I have installed this module in Magento 2.4.1 on my localhost and I have created Test App in the Facebook developer account and setup Client Id and Secret for **Instagram Basic Display API**, I'm using normal login(not popup), the login is working for Facebook but not for the Instagram. 

I have added **Valid OAuth Redirect URIs** as `https://localhost/magento_241/sociallogin/social/callback/?hauth.done=Instagram`

Is there anything I'm missing? Also, I would like to know that does it work on not secure URL(HTTP)?

### Preconditions

1. Magento: 2.4.1
2. PHP: 7.3.21
3. MySQL: 5.7.31

### Steps to reproduce

1. Installed the module in 2.4.1
2. Setup client id and secret in Facebook developer account
3. Configured the module
4. On Frontend, Login using Instagram

### Expected result

1. It should be logged in as an Instagram user

### Actual result

1. It shows below error
![screenshot-newtab-2020 12 31-18_17_33](https://user-images.githubusercontent.com/16268546/103411257-07eb3f00-4b95-11eb-9b4e-5b5744d78747.png)

**Comment by Victor-Mageplaza** [comment]
Hi @MohitRane 

Hope you have a good new week at the beginning of the year.
I'm Victor from Mageplaza. I would like to answer your question.

The API that the module uses is the old Instagram API system (can no longer be registered).
Here, I can see that you are using the new API system. So it makes sense for the module to report that the settings do not correspond to the parameters.

I am updating the code to match the new API (you are using).
Thank you!

Best Regards,
Victor

**Comment by MohitRane** [comment]
Hello @Victor-Mageplaza 

Thank you for your response, Hope you're enjoying the new year vibes as well.
Let me know after updating the code so I can check in my local system.

Many Thanks in Advance.

**Comment by MohitRane** [comment]
Hello @Victor-Mageplaza 

Any update?

**Comment by sajorcf** [comment]
Any updates about this? 

I need to use the new Instagram API Login via Facebook Developers, and it's not working.

It gives me: 
![image](https://user-images.githubusercontent.com/42658985/104781928-60a00780-5751-11eb-9d07-dab88693f142.png)

regards

**Comment by sajorcf** [comment]
Hi.

I'm getting 
![image](https://user-images.githubusercontent.com/42658985/104784228-dad28b00-5755-11eb-840b-4de55dd852dc.png)

When I use my Facebook Developers: Instagram Basic App Id & Secret ID

Regards

**Comment by MohitRane** [comment]
Hello @Victor-Mageplaza 

Any update up till now?
