### ISSUE TITLE
Compatibility with customer approval module

### ISSUE THREAD

**Issue by mkiddo87** [mageplaza/magento-2-social-login#224]
Users that use Social login will bypass customer approval and not get marked as pending

### Preconditions

1. Magento: 2.3
2. PHP: 7
3. MySQL: mysql  Ver 15.1 Distrib 10.3.22-MariaDB, for Linux (x86_64)

### Steps to reproduce
1. Have mageplaza customer approval 
2. Register a new user using email and check that you can't log in without approval
3. User Google or Facebook using Social login and you will bypass the approval check

### Expected result
1. The new user should be marked as pending and the login to magento should get blocked until approved

**Comment by Victor-Mageplaza** [comment]
Hi @mkiddo87 

I'm Victor from Mageplaza. I would like to answer your question.
About your request, I think you should report that to customer approval Github.
The customer approval logic is handled by the customer approval module.
It just needs to confirm the login from SocialLogin to add the handling for that case only. That's an easier way to do.
Thank you!

Best Regards,
Victor

**Comment by mkiddo87** [comment]
Thanks for the clarification, I'll open an issue in the other module then
