### ISSUE TITLE
Error when Login with Instagram (Facebook Developers)

### ISSUE THREAD

**Issue by sajorcf** [mageplaza/magento-2-social-login#225]
### Preconditions
1. Magento: 2.4
2. PHP: 7.4
3. MySQL: 8

### Steps to reproduce
1. Create a Facebook Developers APP
2. Set Instagram Basic
3. Use App ID & Secret ID from Instagram Basic inside module's Instagram config.

### Expected result
1. Log In with Instagram

### Actual result
1. ![image](https://user-images.githubusercontent.com/42658985/104784228-dad28b00-5755-11eb-840b-4de55dd852dc.png)

Hi.

I'm getting "Oops, an error occurred.".

When I use my Facebook Developers: Instagram Basic App Id & Secret ID

Regards

**Comment by KhietNguyen83** [comment]
Thank you for your interest in the SocialLogin module of mageplaza.
Currently Instagram no longer supports the login api, so it is not possible to do login with instagram.
Thank you!
