### ISSUE TITLE
Social Login does't work with Varnish

### ISSUE THREAD

**Issue by paugnu** [mageplaza/magento-2-social-login#234]
Hi,

After having the same issue described in some issues here, I've found why Social Login was not working in my project: the problem was the same described in ticket https://github.com/mageplaza/magento-2-social-login/issues/205

My project data:
- Magento 2.3.4
- Varnish

* Configuration options were correct
* Login would work the first time, but not in subsequent attempts

The problem appeared due to a cached url by varnish. To fix it, I've added the following line:

```
sub vcl_recv {
[...]
     # Bypass shopping cart, checkout and search requests
     if (req.url ~ "/checkout" || req.url ~ "/catalogsearch"  || req.url ~ "/sociallogin") {
        return (pass);
     }
[...]
```

I think it should be interesting adding this note to the README.md file :)

**Comment by Victor-Mageplaza** [comment]
Hi @paugnu,

I'm Victor from Mageplaza.
First of all, thank you very much for your research as well as your contribution.
I will re-check it once and would be happy to update it to UG. Wish you a good day!

Thank you!
Best Regards,
Victor
