### ISSUE TITLE
the "config.php" deployment config file isn't writable

### ISSUE THREAD

**Issue by arun-magento** [mageplaza/magento-2-social-login#238]
copy folder and past  after command run php bin/magento setup:upgrade error show 
-> updating modules: the "config.php" deployment config file isn't writable 
please can you help

**Comment by Victor-Mageplaza** [comment]
Hi @arun-magento ,

I'm Victor from Mageplaza. I would like to answer your question.
You can refer to this article: https://github.com/magento/magento2/issues/26292
Thank you!

Best Regards,
Victor

**Comment by Victor-Mageplaza** [comment]
Hi @arun-magento ,

Allow me to temporarily close the issue.
Please feel free to reopen if you need support
