### ISSUE TITLE
Compare product link inside header links block causes error.

### ISSUE THREAD

**Issue by arunu** [mageplaza/magento-2-social-login#25]
![header_links](https://cloud.githubusercontent.com/assets/3517849/25007809/58191212-207f-11e7-89c2-5c2133f8edfc.jpg)
I am getting this error 

> Cannot read property 'search' of undefined in popup.js in line 97

### Preconditions
1. Magento: 2.1.5
2. PHP: 5.6

### Steps to reproduce
When header link has compare product link, other than register and login links.

### Expected result
The popup should appear on clicking login and register links

### Actual result
Popup doesn't appear and user is redirected to default login and register pages.
The below javascript error occurs:

Fix:
Error occurs because compare product link href is dynamically created.
Checking if href is undefined will fix this issue

Changing 
`if (href.search('customer/account/login') != -1 || href.search('customer/account/create') != -1) {
`
to 
`if (href != undefined && (href.search('customer/account/login') != -1 || href.search('customer/account/create') != -1)) {
` 
will fix the issue.

It would be nice if you could add this condition to project

**Comment by haitv282** [comment]
Thank you very much. We will check and fix it soon.
