### ISSUE TITLE
Class 'Hybrid_Provider_Model_OAuth2' not found

### ISSUE THREAD

**Issue by sheraz-iqbal-zeta** [mageplaza/magento-2-social-login#254]
I just installed this extension from https://github.com/mageplaza/magento-2-social-login,
place in app code folder. running di:compile command getting error

Uncaught Error: Class 'Hybrid_Provider_Model_OAuth2' not found in /var/www/html/sofiqe/app/code/Mageplaza/SocialLogin/Model/Providers/Zalo.php:23

NEED QUICK HELP

![image](https://user-images.githubusercontent.com/100214393/156136766-97c389ea-466a-4185-9384-8af7a6db6f9e.png)

**Comment by sheraz-iqbal-zeta** [comment]
this issue was caused because the lib has not been installed yet. Please follow this link to install the lib to fix your issue: https://github.com/mageplaza/magento-2-social-login/tree/library

Should you have any questions, please let me know!

**Comment by madonzy** [comment]
This repo does not exist anymore https://github.com/mageplaza/magento-2-social-login-library. How can I download lib?

**Comment by KhietNguyen83** [comment]
Hi @madonzy ,
I'm Justin from Mageplaza.
Please dowload library on here: https://github.com/mageplaza/magento-2-social-login/tree/library

**Comment by lexfrost99** [comment]
The "Zip" file is no longer available but I downloaded the Files located at https://github.com/mageplaza/magento-2-social-login/tree/library and uploaded them to the correct location in "lib" but the error still remains 

`Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% 1 sec 87.0 MiB
Fatal error: Uncaught Error: Class 'Hybridauth\Adapter\OAuth2' not found in /home/satanmec/public_html/app/code/Mageplaza/SocialLogin/Model/Providers/Zalo.php:38
Stack trace:
#0 /home/satanmec/public_html/vendor/composer/ClassLoader.php(444): include()
#1 /home/satanmec/public_html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/satanmec/...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Mageplaza\\Socia...')
#3 [internal function]: spl_autoload_call('Mageplaza\\Socia...')
#4 /home/satanmec/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Mageplaza\\Socia...')
#5 /home/satanmec/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Mageplaza\\Socia...', '/home/satanmec/...')
#6 /home/satanmec/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract(Obj in /home/satanmec/public_html/app/code/Mageplaza/SocialLogin/Model/Providers/Zalo.php on line 38
`

**Comment by KhietNguyen83** [comment]
Hi @lexfrost99,
What version are you using?
Please help me to use version 4.1.3 for manual installation.
Thank you!
