### ISSUE TITLE
Social login works on MS Edge but not on Chrome or firefox 

### ISSUE THREAD

**Issue by scathappens** [mageplaza/magento-2-social-login#255]
On MS Edge the social login works as expected, allowing you to login and make purchases.
on chrome or firefox you can login to the site and have a  'my account' area, however when you then try to make a purchase it brings up the original sites login box with no social login options, no matter when you login via social it will not let you complete a purchase 

### Preconditions

1. Magento: 2.3.7

### Steps to reproduce

1. open chrome or firefox
2. load up my website (www.digitaltaxidermy.co.uk)
3. click log in and sign in to your account via the social links (facebook, google, linkdin)
4. add items to the cart 
5. review cart 
6. proceed to checkout
7. standard site sign up/create account box appears 

alternate route
1. open chrome or firefox
2. load up my website (www.digitaltaxidermy.co.uk)
4. add items to the cart 
5. review cart 
6. proceed to checkout
7. social login box pops up 
8. sign in to your account via the social links (facebook, google, linkdin)
9. when signed in the cart returns 
10. click purchase now 
11. standard site sign up/create account box appears 

### Expected result

1. once logged in via social login you should have access to all features granted to signed in users including ability to purchase items without having to make a site specific account as in microsoft edge

### Actual result

1. unable to make purchases without creating a site specific account (within chrome or firefox)

**Comment by KhietNguyen83** [comment]
Hi @scathappens ,
I'm Justin from Mageplaza.
Please add line customerData.reload(true); at line 85 in file view/frontend/web/js/popup.js || https://i.imgur.com/aXf6q94.png
Then check again.
Thank you!
