### ISSUE TITLE
Issue with version 4.1.4

### ISSUE THREAD

**Issue by bohdan-berezhniy** [mageplaza/magento-2-social-login#260]
### Preconditions
1. Magento: 2.4.4
2. PHP: 8.1.4
3. MySQL: 8.0
4. 

### Steps to reproduce
1. Try to log in via Facebook - the first login is successful
2. Open a new incognito window or clear all browser data and repeat 1 step

### Expected result
1. Logged in

### Actual result
1 exception(s):
Exception #0 (Exception): Deprecated Functionality: Facebook\FacebookApp implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in vendor/facebook/graph-sdk/src/Facebook/FacebookApp.php on line 29

Exception #0 (Exception): Deprecated Functionality: Facebook\FacebookApp implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in vendor/facebook/graph-sdk/src/Facebook/FacebookApp.php on line 29
<pre>#1 include() called at [vendor/composer/ClassLoader.php:571]
#2 Composer\Autoload\includeFile() called at [vendor/composer/ClassLoader.php:428]
#3 Composer\Autoload\ClassLoader->loadClass() called at [vendor/facebook/graph-sdk/src/Facebook/Facebook.php:145]
#4 Facebook\Facebook->__construct() called at [vendor/hybridauth/hybridauth/hybridauth/Hybrid/Providers/Facebook.php:63]
#5 Hybrid_Providers_Facebook->initialize() called at [vendor/hybridauth/hybridauth/hybridauth/Hybrid/Provider_Model.php:102]
#6 Hybrid_Provider_Model->__construct() called at [vendor/hybridauth/hybridauth/hybridauth/Hybrid/Provider_Adapter.php:101]
#7 Hybrid_Provider_Adapter->factory() called at [vendor/hybridauth/hybridauth/hybridauth/Hybrid/Auth.php:277]
#8 Hybrid_Auth::setup() called at [vendor/hybridauth/hybridauth/hybridauth/Hybrid/Endpoint.php:129]
#9 Hybrid_Endpoint->processAuthStart() called at [vendor/hybridauth/hybridauth/hybridauth/Hybrid/Endpoint.php:51]
#10 Hybrid_Endpoint->__construct() called at [vendor/hybridauth/hybridauth/hybridauth/Hybrid/Endpoint.php:72]
#11 Hybrid_Endpoint::process() called at [vendor/mageplaza/magento-2-social-login/Controller/Social/Callback.php:56]
#12 Mageplaza\SocialLogin\Controller\Social\Callback->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#13 Mageplaza\SocialLogin\Controller\Social\Callback\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#14 Mageplaza\SocialLogin\Controller\Social\Callback\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#15 Mageplaza\SocialLogin\Controller\Social\Callback\Interceptor->___callPlugins() called at [generated/code/Mageplaza/SocialLogin/Controller/Social/Callback/Interceptor.php:23]
#16 Mageplaza\SocialLogin\Controller\Social\Callback\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#17 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#18 Mageplaza\SocialLogin\Controller\Social\Callback\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#19 Mageplaza\SocialLogin\Controller\Social\Callback\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Apptrian/FacebookPixel/Plugin/App/Action/Context.php:61]
#20 Apptrian\FacebookPixel\Plugin\App\Action\Context->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#21 Mageplaza\SocialLogin\Controller\Social\Callback\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#22 Mageplaza\SocialLogin\Controller\Social\Callback\Interceptor->___callPlugins() called at [generated/code/Mageplaza/SocialLogin/Controller/Social/Callback/Interceptor.php:32]
#23 Mageplaza\SocialLogin\Controller\Social\Callback\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#24 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#25 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#26 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#27 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#28 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#29 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#30 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/amasty/aminvisiblecaptcha/Plugin/Framework/App/FrontControllerInterface/ValidateCaptcha.php:118]
#31 Amasty\InvisibleCaptcha\Plugin\Framework\App\FrontControllerInterface\ValidateCaptcha->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#32 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/mirasvit/module-cache-warmer/src/CacheWarmer/Plugin/Debug/OnHitPlugin.php:140]
#33 Mirasvit\CacheWarmer\Plugin\Debug\OnHitPlugin->aroundAroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#34 Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#35 Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callPlugins() called at [generated/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin/Interceptor.php:23]
#36 Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#37 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#38 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#39 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#40 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#41 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:36]
</pre>

**Comment by ecoprince** [comment]
I also face the same issue with Magento 2.4.4 with PHP 8.1

**Comment by sivajik34** [comment]
Team,
May I know any update on this?
Magento 2.4.5 with php8.1

**Comment by klou** [comment]
It looks like this uses ```hybridauth``` < 3.0, which in turn uses an archived Facebook SDK that is limited to PHP 5.4.x or 7.x.  

As a result, this plugin also can't be installed via Composer on a PHP 8.1 system.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mageplaza/magento-2-social-login[4.1.0, ..., 4.1.5] require hybridauth/hybridauth ^2.14.0 -> satisfiable by hybridauth/hybridauth[v2.14.0, ..., v2.18.0].
    - hybridauth/hybridauth[v2.14.0, ..., v2.18.0] require facebook/graph-sdk ^5.4 -> satisfiable by facebook/graph-sdk[5.4.0, ..., 5.7.0].
    - facebook/graph-sdk[5.4.0, ..., 5.7.0] require php ^5.4|^7.0 -> your php version (8.1.8) does not satisfy that requirement.
    - Root composer.json requires mageplaza/magento-2-social-login ^4.1 -> satisfiable by mageplaza/magento-2-social-login[4.1.0, ..., 4.1.5].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require mageplaza/magento-2-social-login:*" to figure out if any version is installable, or "composer require mageplaza/magento-2-social-login:^2.1" if you know which you need.
```

I think that if the devs migrate the extension to use HybridAuth 3.x (https://hybridauth.github.io/developer-ref-migrating.html), it would solve both the FB and PHP8 issues.

**Comment by fmineo** [comment]
@klou Yes, the issue is FB graph sdk that not support PHP 8.1.

**Comment by magefan** [comment]
[Mageplaza.zip](https://github.com/mageplaza/magento-2-social-login/files/9509311/Mageplaza.zip)

Hello @fmineo @sivajik34 @ecoprince @klou 

Update of this library will help

**Comment by bohdan-berezhniy** [comment]
Hello @klou  @fmineo @sivajik34  @ecoprince 
[Mageplaza.zip](https://github.com/mageplaza/magento-2-social-login/files/9509348/Mageplaza.zip)

Update of this library will help
