### ISSUE TITLE
 Fatal error:  Class 'OAuth2Client' not found in /var/www/html/magento2/app/code/Mageplaza/SocialLogin/Model/Providers/Amazon/AmazonOAuth2Client.php on line 24

### ISSUE THREAD

**Issue by msliman** [mageplaza/magento-2-social-login#27]
When try to run command:
php bin/magento ssetup:di:compile
I got this error 

 Fatal error:  Class 'OAuth2Client' not found in /var/www/html/magento2/app/code/Mageplaza/SocialLogin/Model/Providers/Amazon/AmazonOAuth2Client.php on line 24

**Comment by haitv282** [comment]
Hi there,

If you clone the extension from git, please clone this library also https://github.com/mageplaza/magento-2-social-login-library and place it under folder `lib\internal\Mageplaza\SocialLogin`.
We recommended you install via composer `composer install mageplaza/magento-2-social-login dev-master` or buy our package at https://www.mageplaza.com/magento-2-social-login-extension/

**Comment by msliman** [comment]
@haitv282 I tried it manually and put the library, but got the same error.

**Comment by msliman** [comment]
@haitv282 Thank you, I bought it. and worked fine bit i tried to login with facebook and got this error:
Ooophs, we got an error: Facebook Graph returned an error: This IP can't make requests for that application.

Please help.

**Comment by haitv282** [comment]
Hi there,

After searching on this issue, I saw that it related to Facebook App setting about Whitelist IP address and your host server. Please search this message on the google, you may see the way to solve it.
