### ISSUE TITLE
README Provided Link for "download this zip package" is wrong

### ISSUE THREAD

**Issue by krunal2212** [mageplaza/magento-2-social-login#272]
Hello Mageplaza Team,

The link which you have provided for "[download this zip package](https://github.com/mageplaza/magento-2-social-login-library/archive/master.zip)" is going to https://github.com/mageplaza/magento-2-social-login-library/archive/master.zip and it shows link is invalid, Please check

**Comment by KhietNguyen83** [comment]
Thank you for your interest in the mageplaza extension.
Please help me to download the library here: https://github.com/mageplaza/magento-2-social-login/tree/library
Thank!
