### ISSUE TITLE
Vkontakte auth error

### ISSUE THREAD

**Issue by Tonop** [mageplaza/magento-2-social-login#28]
### Preconditions

1. Magento: 2.1.6
2. PHP:  5.6.26 
3. MySQL: 14.14 Distrib 5.7.15
4. 

### Steps to reproduce

1. User click on Sign in via VKontakte
2. System want to get access to account and offers allow or cancel the request
3. User click allow 

### Expected result

1. User log in to Magento store

### Actual result

1. System show errors
Ooophs, we got an error: User profile request failed! Vkontakte returned an error: exception 'Exception' with message 'The Authorization Service has return: invalid_client' in ..../magento2/lib/internal/Mageplaza/SocialLogin/Hybrid/thirdparty/OAuth/OAuth2Client.php:84

**Comment by haitv282** [comment]
Hi Tonop,

I have checked this issue carefully and saw that it still works normally for me. Please check the VK app setting and the Application Id/Secure Key in Social Login configuration.

**Comment by Tonop** [comment]
Hi Brian,

You are right I made mistake in key sing Service key against Secure key. 
Thanks,

Boris
