### ISSUE TITLE
Facebook login returns HTTP ERROR 500

### ISSUE THREAD

**Issue by Tonop** [mageplaza/magento-2-social-login#32]
### Preconditions

Magento: 2.1.6
PHP: 5.6.26
MySQL: 14.14 Distrib 5.7.15
Module version 2.3.2
### Steps to reproduce

1. Login via FB
2. 
3. 

### Expected result

1. Logged in

### Actual result

1. HTTP ERROR 500

Others login ways such as Google,LinkedIn, Instagram, Vkontakte working correctly.
In version 2.2.0 there was no issues, it worked correctly.

**Comment by haitv282** [comment]
Thank you for noticing us.

This bug caused by HybridAuth change the folder structure of Facebook Library.
Please update to our latest version to solve this problem.

**Comment by Tonop** [comment]
I pulled the 2.3.2 version from github. There is the latest?

**Comment by haitv282** [comment]
Please check it again. The latest version is 2.3.3

**Comment by uileprojecttus** [comment]
i have version 2.3.5 and having the same problem. Any idea?

None of social is loggin in

**Comment by Reroot-nick** [comment]
i have the latest 2.4.0.1 and having the same issue. I tried everything but still is not working.
any ideas?

**Comment by Reroot-nick** [comment]
same issue on 2.5 version, any helps please?
