### ISSUE TITLE
TypeError: Cannot read property 'fn' of undefined  /Z-Wave/ru_RU/Mageplaza_Core/js/owl.carousel.min.js:1

### ISSUE THREAD

**Issue by Tonop** [mageplaza/magento-2-social-login#34]
### Preconditions

Magento: 2.1.6
PHP: 5.6.26
MySQL: 14.14 Distrib 5.7.15
Module Core version 1.0.0

### Steps to reproduce

1. open home page
2. 
3. 

### Expected result

1. no errors

### Actual result

1. [Screenshot, logs]
TypeError: Cannot read property 'fn' of undefined
 /pub/static/frontend/Swinestudio/Z-Wave/ru_RU/Mageplaza_Core/js/owl.carousel.min.js:1
![js](https://cloud.githubusercontent.com/assets/2456408/25382383/0c4f1b2a-29c0-11e7-9af0-68c11fd24506.jpg)

**Comment by haitv282** [comment]
The social login does not use that library. So that error may cause by other extensions. Please submit a ticket to https://mageplaza.freshdesk.com and let us know which extension are you using. We will check and let you know how to solve it.
