### ISSUE TITLE
Class 'Hybrid_Auth' not found

### ISSUE THREAD

**Issue by Mohd-Salman** [mageplaza/magento-2-social-login#35]
In Magento 2 error shows when i click on social buttons.

> Class

 'Hybrid_Auth' not found in 

> 

/app/code/Mageplaza/SocialLogin/Model/Social.php on line 188

**Comment by haitv282** [comment]
If you clone the extension from git, please clone this library also https://github.com/mageplaza/magento-2-social-login-library and place it under folder lib\internal\Mageplaza\SocialLogin.
We recommended you install via composer composer install mageplaza/magento-2-social-login or buy our package at https://www.mageplaza.com/magento-2-social-login-extension/

**Comment by Mohd-Salman** [comment]
I put the library as you mentioned in the above comment and i filled the details in the admin panel for Facebook and google but when i click on the login button then pop up one with 404 page not fount error.
please check the below url.
http://alfasoftdemo.com/en/sociallogin/social/login/type/facebook/
