### ISSUE TITLE
[Improvement] Show login buttons on checkout

### ISSUE THREAD

**Issue by lcsbaroni** [mageplaza/magento-2-social-login#38]
On checkout page, the buttons to login are not shown.

Would be very good if have this option on admin to add buttons on this page.
Checkout is one of more important pages and I believe that option wil increase the conversion.

thanks

**Comment by imsamthomas** [comment]
Hi,

There is no option showing that button in default checkout but it is ready compatible with Mageplaza one step checkout https://www.mageplaza.com/magento-2-one-step-checkout-extension/

Regards,
Sam

**Comment by lcsbaroni** [comment]
Ok, thanks.
