### ISSUE TITLE
[Resolved] Social Login Magento 2 Popup doesn't work

### ISSUE THREAD

**Issue by imsamthomas** [mageplaza/magento-2-social-login#39]
Hey there,

I just installed your Social Login extension on Magento 2 but for some reason i can’t get the popup to work. Am i missing something? Any help would be appreciated.

Thanks

**Comment by imsamthomas** [comment]
We have made it compatible with Porto theme. you can download the latest version https://github.com/mageplaza/magento-2-social-login/

=> [Fix patch](https://github.com/mageplaza/Magento-2-Social-Login-Extension/blob/master/view/frontend/layout/default.xml#L30)

## How to fix:

### Solution #1: 

Open file: `app/design/frontend/Smartwave/porto/Smartwave_Porto/layout/default.xml`

Remove:
```
<block class="Magento\Customer\Block\Form\Login" name="header_customer_form_login" template="Smartwave_Porto::html/login.phtml"/>
```
![social-remove-porto](https://cloud.githubusercontent.com/assets/2810172/26081328/7e0b0cb2-39f4-11e7-94e8-463892ed8834.png)



### Solution 2:

Open file: [/view/frontend/layout/default.xml](https://github.com/mageplaza/Magento-2-Social-Login-Extension/blob/master/view/frontend/layout/default.xml#L30)

Add the following block XML in body tag

```
 <!-- Fix Porto Popup login -->
        <referenceBlock name="header_customer_form_login" remove="true"/>
```

Old topic: https://mageplaza.freshdesk.com/support/discussions/topics/6000041167/

**Comment by sumeetmobiwebtech** [comment]
i am using my custom theme but popup does not open
