### ISSUE TITLE
error after connect with facebook

### ISSUE THREAD

**Issue by tal-girit** [mageplaza/magento-2-social-login#4]
<script type="text/javascript">
                try{
                    window.opener.location.href="http://eldar-import.com/customer/account/edit/";
                } catch(e){
                    window.opener.location.reload(true);
                }
                window.close();
            </script>1 exception(s):
Exception #0 (InvalidArgumentException): Invalid return type

Exception #0 (InvalidArgumentException): Invalid return type
#0 /var/www/kushiesbaby_eldarimport/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#1 /var/www/kushiesbaby_eldarimport/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#2 {main}

**Comment by imsamthomas** [comment]
Hi,

Tell us more about your environment:
- Magento version
- Magento mode
- php error report mode
- php version

We will invest further information.

Regards,
Sam
