### ISSUE TITLE
Getting an error while installed mageplaza/magento-2-social-login.

### ISSUE THREAD

**Issue by sup077** [mageplaza/magento-2-social-login#40]
### Preconditions

1. Magento: 2.1.6
2. PHP: 4.0.10.18
3. MySQL: 5.1.73
4. 

### Steps to reproduce

1. Installed social login pluging according to the steps which was given by you.
 

### Expected result

1. Social login sites like facebook, twitter or more shown on the home page

### Actual result

1. [Screenshot, logs]
Fatal error: Class 'Mageplaza\Core\Helper\AbstractData' not found in /home/jkbinfot/public_html/jindeal.com/app/code/Mageplaza/SocialLogin/Helper/Data.php on line 30

**Comment by imsamthomas** [comment]
Magento 2 does not support PHP < 5.6, kindly check.

You should remove var/di/ folder to make sure it working

**Comment by sup077** [comment]
Hello Sam
I  removed var/di/ folder and still my project is working properly. Now whats the next step?
Thanks & Regards
Supriti Kashyap

**Comment by sup077** [comment]
Hii Sam 
Let me confirm you one thing, here I am using (PHP Version	7.0.19) for my ecommerce site on magento 2.1.6 .
Thanks & Regards
Supriti Kashyap

**Comment by imsamthomas** [comment]
Please submit a ticket to https://mageplaza.freshdesk.com/ our technical team will look into this.

**Comment by sup077** [comment]
Hey Sam
I facing another issue after enable core and Social Login extension in Mageplaza. While I am running "php bin/magento setup:di:compile" it shows below error. 
Fatal error: Class 'Hybrid_Provider_Model_OAuth2' not found in /home/jkbinfot/public_html/jindeal.com/app/code/Mageplaza/SocialLogin/Model/Providers/GitHub.php on line 13
Please help me to resolve this error.
Thanks & Regards
Supriti Kashyap.

**Comment by haitv282** [comment]
Hi Supriti,

We are so sorry for late reply.
The problem which you got is caused by missing Social Login Library. Please pull it from https://github.com/mageplaza/magento-2-social-login-library and place to folder `lib\internal\Mageplaza\SocialLogin`.
We highly recommended you install the extension via composer `composer require mageplaza/magento-2-social-login` or download from our site https://www.mageplaza.com/magento-2-social-login-extension/

Thank you very much.

**Comment by sup077** [comment]
Hello Guys,
 I am facing
"Ooophs, we got an error: Notice: Undefined index: oauth_token in /home/jkbinfot/public_html/jindeal.com/lib/internal/Mageplaza/SocialLogin/Hybrid/thirdparty/OAuth/OAuth1Client.php on line 85"
this issue after enable twitter social login in magento 2.1.6 .
Let me clear one thing, do I need different oath files for enabling each social login account?
Somebody please help me to resolve this issue as soon as possible.
Thanks & Regards
Supriti Kashyap

**Comment by sup077** [comment]
Hey Sam, 
Do I need to upload individual Social Login file in lib folder for enabling any social login panel?

**Comment by gixid192** [comment]
Hi Supriti,

The problem you are having with Twitter is because of your secret, client key/id is not correct.
Please check those info again.

Thank you very much.

**Comment by arjun1992** [comment]
Hello @sup077 ,

Sorry for the late reply. This issue is due to undefined callback URL. You can add any callback url in your twitter configuration such as https://dev.twitter.com/

**Comment by careerbeeps** [comment]
Hello Team, 

I have installed the extension and when I try to login with either facebook or google, it shows this error: http://prntscr.com/jiy71s

Any solution?
