### ISSUE TITLE
Fatal Error occur able ebable Mazeplaza extension.

### ISSUE THREAD

**Issue by sup077** [mageplaza/magento-2-social-login#41]
Hello Team Mageplaza
I facing an issue while running setup:di:compile command. The error is :
Fatal error: Class 'Hybrid_Provider_Model_OAuth2' not found in /home/jkbinfot/public_html/jindeal.com/app/code/Mageplaza/SocialLogin/Model/Providers/GitHub.php on line 13
Kindly help me to sort it out as soon as possible.
Thanks & Regards
Supriti Kashyap

**Comment by haitv282** [comment]
Hi Supriti,

Please read the answer on #40
