### ISSUE TITLE
[Improvement] Connect to existing account when customer is logged in

### ISSUE THREAD

**Issue by kolucciy** [mageplaza/magento-2-social-login#43]
### Preconditions
As a store owner I want to add a new page "Connect Social Accounts" under Customer Account Menu, which has Social Login buttons in order to offer my customers an option to link their Social Accounts.

### Steps to reproduce
1. As a customer I login with my existing Magento Account.
2. As a customer I click on one of the "Connect" buttons in order to link my Social Account with my Magento Account

### Expected result
As a customer I remain logged in with new Social Account linked

### Actual result
As a customer I get logged out and then logged in again as a different customer

**Comment by haitv282** [comment]
Hi Kolucciy,

We highly appreciate any ideas, suggestions and comments like yours and consider them in our next improvement to make our products better. Thank you very much!
