### ISSUE TITLE
Ooophs, we got an error: User profile request failed! Facebook returned an error...

### ISSUE THREAD

**Issue by evagabond** [mageplaza/magento-2-social-login#44]
Hello,
I am getting the following error:

> Ooophs, we got an error: User profile request failed! Facebook returned an error: Error validating access token: The user has not authorized application

### Preconditions

1. Magento: 2.1.2
2. PHP: 7.0.17
3. MySQL: Ver 14.14 Distrib 5.6.35-80.0, for Linux (x86_64) using  6.0

### Steps to reproduce

1. Facebook Social Login is working fine in the first attempt.
2. Once I cancel the account and delete the access permission from my Facebook App setting at: https://www.facebook.com/settings?tab=applications then again try to Sign Up using Facebook Social Login I am getting the above error.

### Expected result

1. Instead of getting the above error I should have been able to Sign Up again using Facebook Social Login.

### Actual result

1. [Screenshot, logs]
![selection_001](https://cloud.githubusercontent.com/assets/25109212/26826004/f4c647ca-4ad6-11e7-8f22-c013ea5b89dd.png)
**Clearing the browser's cookie or trying in Anonymous Mode seems to be working. But without doing that the above error occurs.**

**Comment by haitv282** [comment]
Hi,
Thank you for noticing us. I will note it to our developer team consider to check and solve it in the next release.
