### ISSUE TITLE
Invalid block type

### ISSUE THREAD

**Issue by lns-johnaaron** [mageplaza/magento-2-social-login#45]
### Preconditions

1. Magento:  2.1.2
2. PHP: 5.6.30
3. MySQL: 5.0.11

### Steps to reproduce

1. Download Mageplaza SocialLogin
2. Copy to app/code
3. php bin/magento setup:upgrade
4. php bin/magento setup:static-content:deploy

### Expected result
1.  Working Socail Login

### Actual result

1. Error appear

![image](https://user-images.githubusercontent.com/27260706/27316223-ea19a328-55b0-11e7-804c-4af5c0a62443.png)

Need assistance on this one please.

**Comment by haitv282** [comment]
Hi there,

Please remove all of the extension code, flush Magento cache and reinstall it again.
You should download the extension from our site http://mageplaza.com or install via composer `composer require mageplaza/magento-2-social-login`.
Thank you very much.
