### ISSUE TITLE
Cannot use Facebook login function

### ISSUE THREAD

**Issue by acyh** [mageplaza/magento-2-social-login#47]
After I followed the step in user guideline (create Facebook app and enabled the login function),  I can saw the Facebook login button in the FrontEnd. However, it shows "500 Internal Server Error" which can not show normal Facebook login dialog,

### Preconditions
1. Magento: 2.1.6
2. PHP: 5.6.12
3. MySQL:  5.7.18

### Steps to reproduce
1. Click the Facebook login button.
2. Dialog pop up shown

### Expected result
1. The popup should be Facebook login popup 

### Actual result
1. The popup box link is :http:/domain/sociallogin/social/login/type/facebook/
And It show 500 "500 Internal Server Error"
![image](https://user-images.githubusercontent.com/29795422/27731229-c474d118-5dbe-11e7-92c0-aa4e21b9d6e6.png)

**Comment by gixid192** [comment]
Hi @acyh 
I suggest you check again your store's cache.
Make sure you follow the correct steps after intalling the module.

Here is what I suspect:
- You are having cache issue, after re-deploying, your store doesn't know it needs to use the new files
- Some files are missing, maybe the lib folder is missing. Please check again your copy process.

You need to backup your store before running any of the following commands

To fix the first issue:
- Makre sure you don't have any cahe managent active in your server
- Run this command: rm -rf pub/static/adminhtml/ pub/static/frontend/ pub/static/_cache/ pub/static/_requirejs/ var/generation/* var/di/* var/cache/*
- deploy your store again.

Please update me the result. Thank you.

**Comment by acyh** [comment]
May I know what is the meaning for "deploy your store again"?
It means run "php bin/magento setup:di:compile" ? or ?

**Comment by gixid192** [comment]
Hi @acyh 
Here is the deploy command: php bin/magento setup:static-content:deploy, if you use other languages than english, you need to add the language's code as a parameter
php bin/magento setup:static-content:deploy en_GB

**Comment by acyh** [comment]
Hi @gixid192 
I followed your fix but still got some performance

**Comment by gixid192** [comment]
Hi @acyh 
I'm not sure why you mentioned something about performance.

The main issue is 500 error when trying to login with facebook. Is it gone now? Could you login now?
Please also give me some more details about the performance issue.

Thank you.

**Comment by acyh** [comment]
Hi @gixid192 ,
Sorry for the typo mistake.
I followed your fix but still got same error

**Comment by gixid192** [comment]
Hi @acyh 

I will need to see your log file. Here is how you get it.
- Navigating to var/log folder, backup all of the contents or you can just remove it
- Then try to logging with Facebook again, the purpose is to reproduce the error again so that it will write the error into log folder
- Now you open the var/log folder again, zip alll the files, upload it to driver or any host, give me the link, I will download and check the log for you.

**Comment by acyh** [comment]
Hi @gixid192 ,
I have backed debug.log, exception.log, install.log and system.log and removed all from var/lo.
However, no new log file generated after I tried to log with Facebook again

**Comment by gixid192** [comment]
Hi @acyh 

So your store are in production mode or does not enable log
Please submit a ticket here; https://mageplaza.freshdesk.com/
We need to access to your server to fix this issue, we will need SSH and Admin credentials info. That's the reason you need to submit a ticket.

**Comment by gixid192** [comment]
@ibecmattb did you try all the things I suggest above?

**Comment by devqualwebs** [comment]
Hello @gixid192 ,
I'm also facing same issue in my magento website, I'm using Magento v2.1.3.
Installed and configured the extension. Tried static-content:deploy as well as cache clean.
But its showing 500 internal server error again and again.
