### ISSUE TITLE
Registration form Not Open in popup

### ISSUE THREAD

**Issue by vedendrasingh** [mageplaza/magento-2-social-login#49]
I was try to open registration form on popup but it not working please suggest

**Comment by MaxxLuong** [comment]
Hi Vedendrasingh,

We are so sorry for late reply.
Make sure you are using the latest version. In admin, "Popup Links Selector" configuration field has the value of ".header .links, .section-item-content .header.link".
If you use a theme other than the default theme.We need access it to check the problem.
Thank you very much.
