### ISSUE TITLE
Fatal error: Class 'Hybrid_Provider_Model_OAuth2' not found in magento2\app\code\Mageplaza\SocialLogin\Model\Providers\Amazon.php on line 22

### ISSUE THREAD

**Issue by akash-uniterrene** [mageplaza/magento-2-social-login#54]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. SocialLogin

### Steps to reproduce

1. Unzip plugin and upload to add/code/mageplaza folder
2. run commend
 - php bin/magento setup:upgrade 
-  php -dmemory_limit=512M bin/magento setup:di:compile

I got error
- Fatal error: Class 'Hybrid_Provider_Model_OAuth2' not found in C:\xampp\htdocs\cpapsales\magento2\app\code\Mageplaza\SocialLogin\Model\Providers\Amazon.php on line 22

### Actual result

1.(https://user-images.githubusercontent.com/25543268/29362739-c12041d0-82aa-11e7-953a-6bb47ab26538.png)
]

**Comment by MaxxLuong** [comment]
Hi,
The problem which you got is caused by missing Social Login Library. Please pull it from [https://github.com/mageplaza/magento-2-social-login-library](https://github.com/mageplaza/magento-2-social-login-library) and place to folder lib\internal\Mageplaza\SocialLogin
Thank you very much.

**Comment by manishiitg** [comment]
> Hi,
> The problem which you got is caused by missing Social Login Library. Please pull it from https://github.com/mageplaza/magento-2-social-login-library and place to folder lib\internal\Mageplaza\SocialLogin
> Thank you very much.

Thanks, it solved my issue.

**Comment by keke996** [comment]
> > 嗨，
> > 您遇到的问题是由于缺少社交登录库引起的。请从[https://github.com/mageplaza/magento-2-social-login-library中](https://github.com/mageplaza/magento-2-social-login-library)提取它，并将其放置到文件夹lib \ internal \ Mageplaza \ SocialLogin中
> > 。非常感谢。
> 
> 谢谢，它解决了我的问题。

hei,
same error in my web.But https://github.com/mageplaza/magento-2-social-login-library is 404,can you share files to me?

**Comment by shyaaam** [comment]
> > > 嗨，
> > > 您遇到的问题是由于缺少社交登录库引起的。请从[https://github.com/mageplaza/magento-2-social-login-library中](https://github.com/mageplaza/magento-2-social-login-library)提取它，并将其放置到文件夹lib \ internal \ Mageplaza \ SocialLogin中
> > > 。非常感谢。
> > 
> > 
> > 谢谢，它解决了我的问题。
> 
> hei,
> same error in my web.But https://github.com/mageplaza/magento-2-social-login-library is 404,can you share files to me?

https://github.com/mageplaza/magento-2-social-login
