### ISSUE TITLE
Clicked on sign in with amazon and got this error. Ooophs, we got an error: Missing required argument $providerId of Mageplaza\SocialLogin\Model\Providers\Amazon

### ISSUE THREAD

**Issue by aniruddh-capital** [mageplaza/magento-2-social-login#55]
### Preconditions

1. Magento: 2.1.5
2. PHP: 5.7
3. MySQL: 
4. 

### Steps to reproduce

1. Add item to cart
2. Go to checkout
3. Click on sign in with amazon

### Expected result

1. It should open Amazon login popup

### Actual result

1. It shows this error:
Ooophs, we got an error: Missing required argument $providerId of Mageplaza\SocialLogin\Model\Providers\Amazon

**Comment by gixid192** [comment]
Hello,

It looked to me that you are using an old version of our extension. Please pull the latest code to fix the current issue.
It's working well in my local machine, you can check my video here: https://www.screencast.com/t/BseELu2ONXP
