### ISSUE TITLE
Base table or view not found: 1146 Table 'magento_eshop_dev.mageplaza_social_customer' doesn't exist

### ISSUE THREAD

**Issue by vctqs1** [mageplaza/magento-2-social-login#56]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by MaxxLuong** [comment]
Hi,

The problem which you got is caused by command "php bin/magento setup:upgrade"  is not complete.Please try running "php bin/magento setup:di:compile" and check it.

Thank you very much.
