### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by pc2day** [mageplaza/magento-2-social-login#59]
Hey Guys,

I have installed Magento 2.1.5 a while ago with the Social Login Plugin.
Worked somewhat okay, but sometimes i had some problems.

Recently i updated to 2.1.8 but the problem is still there, i hope that you guys can help me out here.

The problem is that while loading a page on the frontend sometimes it stoppes right in the middle,..
all JS scripts are then not working and looks like the page is waiting for something (loading is done though).

In developer mode (browser) it is giving a Uncaught TypeError,..
But when i refesh the page a couple of times it is loading ok,..

The Error i am getting is;

![error](https://user-images.githubusercontent.com/31862543/30290183-c43af8e0-972e-11e7-8ba2-b64f26b2f7c9.PNG)

I hope that you guys can help me out here.

Thanks!

Greetings Wouter

**Comment by MaxxLuong** [comment]
Hi pc2day,
It seems the problem just happen on your site.We need site link to check the problem. Please provide it for us.
Thank you very much.

**Comment by pc2day** [comment]
Hi there,

Thanks for the fast answer.
Of course here it is; http://www.scrapamoment.nl/

**Comment by pc2day** [comment]
Most of the time the problem is occurring in Google Chrome, don't know why but it does,..

**Comment by MaxxLuong** [comment]
Hi pc2day,
You are using an old version of our extension. You can see at this:  [http://prntscr.com/gk2gdu](http://prntscr.com/gk2gdu).Please pull the latest code to fix the current issue. 
link download: [https://github.com/mageplaza/module-core](https://github.com/mageplaza/module-core)
Thank you very much.

**Comment by pc2day** [comment]
Hi,

Thanks, I will try that this evening!
I will let you know what the results are :)
