### ISSUE TITLE
Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by GuerrillaCoder** [mageplaza/magento-2-social-login#61]
### Preconditions

1. Magento: 2.1.6
2. PHP: 7.0.2
3. MySQL: 5.6

### Steps to reproduce

1.  install module
2. configure search console
3. try to login

### Expected result

1. logs in

### Actual result

This error occurs:

![image](https://user-images.githubusercontent.com/11444395/30620387-fd36650c-9d9c-11e7-902a-77fd8a6fd57d.png)

I have configured the callback url exactly in search console as can be seen here:

![image](https://user-images.githubusercontent.com/11444395/30620473-75f3a158-9d9d-11e7-99c2-a397126b131d.png)

Callback urls is exactly the same as in the modules admin settings and error message gives exact same url.

Is module tagging a different URL or something?

**Comment by GuerrillaCoder** [comment]
issue was someone had changed token

**Comment by engrKaka** [comment]
I am facing approximately similar error, plugin was working fine on my localserver but when I pushed it to stage (SSL enabled) now it is showing me that error, while the redirect uri has been configured correctly,
