### ISSUE TITLE
Social login Popup is not working on Ultimo theme in Magento 2

### ISSUE THREAD

**Issue by imsamthomas** [mageplaza/magento-2-social-login#62]
We have received an issue that is not working on [Ultimo theme](https://themeforest.net/item/ultimo-fluid-responsive-magento-theme/3231798?ref=mageplaza)  ([Demos](http://ultimo.infortis-themes.com/demo/select-demo/)) by Vinay (vinay19.....r@y.....com) 
We would like to share this solution to Mageplaza community.

In this issue, @MaxxLuong will show you how to resolve this step by step.

**Comment by MaxxLuong** [comment]
I'm Maxx from Mageplaza.I will support you in this problem. 
Firstly, Please enable Social Login in Configuration, follow the steps:

1. Comment out  block "social_login_custom_style"  in the file:
/vendor/mageplaza/magento-2-social-login/view/frontend/layout/default.xml
![image](https://user-images.githubusercontent.com/16910940/30678985-57fdb192-9ec0-11e7-84fa-e46efe8883b5.png)
 
2. Add the "social_login_custom_style"" block in file:
/app/design/frontend/Infortis/ultimo/Infortis_Ultimo/layout/default.xml
![image](https://user-images.githubusercontent.com/16910940/30678370-06a48e14-9ebc-11e7-9485-9116f4da51e7.png)

3. Add style below in "Custom CSS" configuration fields:

```
button#bnt-social-login-authentication {
		border: none !important;
	}
	div#social-login-popup button.mfp-close {
		border: none !important;
	}
```

![image](https://user-images.githubusercontent.com/16910940/30679401-83e4903e-9ec3-11e7-9e0b-4bd41f3034ff.png)

4. Save and flush cache.

 Thank you very much!
