### ISSUE TITLE
Google wont approve this module

### ISSUE THREAD

**Issue by GuerrillaCoder** [mageplaza/magento-2-social-login#64]
Recently Google have made it so you have to request non-standard scopes so I am unable to get this module working.  It just gives an "unverified error".  I tried to find your code where you define Google scopes and this seems to be only page in repo they are defined:

https://github.com/mageplaza/magento-2-social-login-library/blob/master/Hybrid/Providers/Google.php

The scopes defined are:

    public $scope = "https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.profile.emails.read https://www.google.com/m8/feeds/";

Google will not approve `https://www.google.com/m8/feeds/` without an explanation why it is needed.

Thie google docs define this scope as `read/write access to Contacts and Contact Groups`.  Why does a login module need to read and write a users contacts?

Line 198 method `getUserContacts()` appears to be where it is used so I guess this is where the issue is.  I haven't gone through code in detail but I guess it is taking all of their contacts?  Isn't this beyond what a login module should do?  

How do I justify this so google can approve this scope so your module works?

**Comment by MaxxLuong** [comment]
I’m not sure that I can understand your issue, so could you please send me some screenshots and admin backend access information of your website by create a ticket here  [ https://mageplaza.freshdesk.com/](https://mageplaza.freshdesk.com/).Thank you very much!

**Comment by GuerrillaCoder** [comment]
What don't you understand?  Google wont approve m8/feed without an explanation of why a login module needs to download and edit every users contacts. Since July this permission needs to be approved by Google manually.

Please explain to me the part of this you do not understand.

**Comment by haitv282** [comment]
Hi @GuerrillaCoder 
The problem was solved on our latest version 2.5.0. Please upgrade the extension and test it again.
Thank you very much.
