### ISSUE TITLE
[How-to] Mageplaza Social Login vs Google Recaptcha

### ISSUE THREAD

**Issue by imsamthomas** [mageplaza/magento-2-social-login#65]
We - Mageplaza got a ticket related to Recaptcha:

---
Hi ,

I'm using your [Magento 2 Social login extension](https://www.mageplaza.com/magento-2-social-login-extension/) and [Magento 2 Google Invisible reCaptcha from Amasty](https://amasty.com/google-invisible-recaptcha-for-magento-2.html). I need to add captcha to Create an Account page. 

Please help me to add captcha and is your extension compatible with it.

Thanks & Regards,
Raminda

![image](https://user-images.githubusercontent.com/2810172/30900616-e145be90-a38e-11e7-981b-3fcf949fe09f.png)

---

@MaxxLuong please show Mageplaza community how to make it compatible.

**Comment by MaxxLuong** [comment]
Firstly, Please enable Social Login in Configuration, follow the steps:

### Step 1 : Go to _`Stores > Settings > Configuration > AMASTY EXTENSIONS > Google Invisible Captcha`_. 

You need to edit the configuration fields  **Urls to enable** and **Selectors for forms**: 

- _`Urls to enable`_:
```
customer/account/createpost
sociallogin/popup/create
```

- _`Selectors for forms`_:
```
.form-customer-create
.form-create-account
```
![image](https://user-images.githubusercontent.com/16910940/32872883-abf94c76-cabb-11e7-9cdd-29cfbe4da47c.png)

### Step 2 :  

-  Check if the SocialLogin extension is enabled/disabled:
>Amasty\InvisibleCaptcha\Helper\Data.php
```
    public function isMageplazaSocialLogin()
    {
        return $this->_moduleManager->isOutputEnabled('Mageplaza_SocialLogin');
    }
```
![image](https://user-images.githubusercontent.com/16910940/32873998-000ebcf0-cac2-11e7-8c82-15bbf7ff6c4a.png)

-  Then in block file you can use following code to get method _isMageplazaSocialLogin_, and create a new method _isCreatePage_ 

> Amasty\InvisibleCaptcha\Block\Captcha.php

![image](https://user-images.githubusercontent.com/16910940/32874184-420985e4-cac3-11e7-81c6-906d84d00837.png)

```
   public function isMageplazaSocialLogin()
    {
        return $this->helper->isMageplazaSocialLogin();
    }
    /**
     * @return bool
     */
    public function isCreatePage()
    {
        if($this->_request->getFullActionName() === "customer_account_create")
        {
        	return true;
        }
        return false;
    }
```

### Step 3 :   Edit template file 
>Amasty\InvisibleCaptcha\view\frontend\templates\amcaptcha.phtml

- onloadCallback

![image](https://user-images.githubusercontent.com/16910940/32874472-05870716-cac5-11e7-8b28-9b936d48ba66.png)

```
var onloadCallback = function () {
            window.formToProtectOnPage.innerHTML +=
                '<input type="hidden" id="amasty_invisible_token" name="amasty_invisible_token" value=""/>';
            require(['jquery', 'mage/mage'], function ($) {
                window.validationForInvisibleCaptchaForm = $('#' + window.formToProtectOnPage.id);
            });
            var id = "<?php echo $block->getData('id'); ?>";
            window.mageplaza = "<?php echo $block->isMageplazaSocialLogin();?>";
            window.createPage = "<?php echo $block->isCreatePage();?>";

            if (!id) {
                if( window.mageplaza === "1" && window.createPage != "1"){
                    id = document.getElementById('amasty_invisible_token').form.querySelector("[type='button']");
                }else{
                    id = document.getElementById('amasty_invisible_token').form.querySelector("[type='submit']");
                }
            }
            grecaptcha.render(id, {
                'sitekey': '<?php echo $block->getSiteKey(); ?>',
                'callback': onSubmit
            });
        };
```
- onSubmit

![image](https://user-images.githubusercontent.com/16910940/32877599-d9e03bd6-cad4-11e7-82c8-4528414ef8ed.png)

```
      var onSubmit = function (token) {
            if(window.mageplaza === "1" && window.createPage!=="1"){
                document.getElementById('amasty_invisible_token').setAttribute('value', token);
                jQuery('#social-login-popup').socialpopup('processCreate');
            }else{
                if (window.validationForInvisibleCaptchaForm.valid()){
                    document.getElementById('amasty_invisible_token').setAttribute('value', token);
                    document.getElementById('amasty_invisible_token').form.submit();
                } else {
                    grecaptcha.reset();
                }
            }
        };

```
### Step 4 :   Edit js file 
>Mageplaza\SocialLogin\view\frontend\web\js\popup.js

- initObserve

![image](https://user-images.githubusercontent.com/16910940/32877777-b7068042-cad5-11e7-9572-795ad18b1b64.png)
 
- processCreate

![image](https://user-images.githubusercontent.com/16910940/32877981-a26e620c-cad6-11e7-8fe1-1370c74d7393.png)

```
 if (!this.createForm.valid()) {
       grecaptcha.reset();
       return;
  }

```
### Step 4 :   Flush cache and reload Browser

![image](https://user-images.githubusercontent.com/16910940/32879145-66d94ef0-cadb-11e7-874b-888f78aa9855.png)
