### ISSUE TITLE
Not working when Allow Guest Checkout > No

### ISSUE THREAD

**Issue by vinaykumar9999** [mageplaza/magento-2-social-login#66]
Native Login Popup is coming when Allow Guest Checkout Option is set to "No"

### Steps to reproduce
1.  Pop Up is not showing up when Sales > Checkout >Checkout Options > Allow Guest Checkout > No 

### Expected result
1.  Mazeplaza Popup will have to show up in place of Native Popup

![native login popup](https://user-images.githubusercontent.com/32778866/31853809-c5d69bf8-b6ac-11e7-9e6c-5ce90003d94a.png)

**Comment by MaxxLuong** [comment]
Hi vinaykumar9999,
You need to select "Customer Authentication Popup" in the configuration. [http://prntscr.com/h18icf](http://prntscr.com/h18icf)

**Comment by vinaykumar9999** [comment]
Hi Maxx

That option is already selected. But still it is not showing up the Social Login Popup.  Please have a look on the screenshot. 

![s popup](https://user-images.githubusercontent.com/32778866/31998079-0e57c2b0-b9ac-11e7-8aff-836df903a980.png)


Regards
Vinay

**Comment by MaxxLuong** [comment]
Thank you for your feedback.
As stated in the ticket, It just adds social login button to "Customer Authentication Popup".
We highly appreciate any ideas, suggestions and comments like yours and consider them in our next improvement to make our products better.
