### ISSUE TITLE
"Invalid signed-request: Missing required parameter 'sig'"

### ISSUE THREAD

**Issue by gh-darvishani** [mageplaza/magento-2-social-login#68]
1. Magento: 2.2
2. PHP: 7.1
 Hi ...when i connect to instagram get this error 
`User profile request failed! Instagram returned an invalid response. Invalid signed-request: Missing required parameter 'sig'
`
how i can fix this error

**Comment by haitv282** [comment]
Hi there,

The issue that you reported has been fixed in the latest version. Could you please upgrade the extension and check it again?
Have a nice day.

**Comment by gh-darvishani** [comment]
Hi 
i do it ... instagram worked very well but google returned this error
`
Ooophs, we got an error: User profile request failed! Google returned an invalid response:stdClass::__set_state(array( 'error' => stdClass::__set_state(array( 'errors' => array ( 0 => stdClass::__set_state(array( 'domain' => 'usageLimits', 'reason' => 'accessNotConfigured', 'message' => 'Project 519568229711 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=519568229711 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.', 'extendedHelp' => 'https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=519568229711', )), ), 'code' => 403, 'message' => 'Project 519568229711 is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=519568229711 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.', )), ))
`
