### ISSUE TITLE
After Social login,product is not adding to wishlist niether not redirecting to wishlist page

### ISSUE THREAD

**Issue by gunjali-agarwal** [mageplaza/magento-2-social-login#69]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. Add item to wishlist.
2. It asks you to login.Choose social Login.Fill credentials.
3. Redirecting to dashboard without adding item to wishlist.

### Expected result

1. It should add item to wishlist and should redirect to wishlist page not to dashboard.

### Actual result

1. Redirecting to dashboard without adding item to wishlist. Default magento login giving correct result.

**Comment by gunjali-agarwal** [comment]
Please fix it as soon as possible.

**Comment by MaxxLuong** [comment]
I have checked this issue and found that:
After the customer chooses Social Login, fill in credentials, then log in. Customer will be redirected to the wishlist page or current page. Then, they can add the product to wishlist.
You can send a ticket to our team here [https://mageplaza.freshdesk.com/](https://mageplaza.freshdesk.com/). We will help you fix the issue "redirect".
In the problem "add wishlist", we will consider this problem in the next version.
Thank you!
