### ISSUE TITLE
Error in debug mode

### ISSUE THREAD

**Issue by Tegos** [mageplaza/magento-2-social-login#7]
PHP Fatal error:  Class 'Mageplaza\\SocialLogin\\Hybrid\\DateTime' not found in /Mageplaza/SocialLogin/Hybrid/Logger.php on line 63

**Comment by Tegos** [comment]
Problem with DateTime & DateTimeZone classes

**Comment by Tegos** [comment]
Also exists problem on this line
print_r($object, true) . PHP_EOL im Logger.php

PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 785907712 bytes)

**Comment by nntoan** [comment]
Please add a backslash before initialisation of DateTime & DateTimeZone.
It should looks like this:

`new \DateTime` & `new \DateTimeZone`

**Comment by samnait** [comment]
is this for the problem they are having with facebook new API?

**Comment by imsamthomas** [comment]
Yes, we are trying to resolve this ASAP and update all customers.

**Comment by nntoan** [comment]
@imsamthomas Facebook provider problem came from old and outdated Facebook PHP SDK. Could you take a look into my pull request?
