### ISSUE TITLE
Social Login Compatibility with Hybridauth v 3.0.0 

### ISSUE THREAD

**Issue by vinaykumar9999** [mageplaza/magento-2-social-login#70]
### Steps to reproduce

1. Pre Installed Hybridauth v 3.0.0 with some other extension  

Tried to install via composer and manually both but the extension is not installing on preinstalled hybridauth v3.0.0

**Comment by Kenny1994** [comment]
Hi,
I'm Kenny from Mageplaza.
Regarding your reported issue, we haven't tested with Hybridauth v 3.0.0 yet,
However, if you want to update Hybrid, you should replace this registration.php file with the new one.
![screenshot_209](https://user-images.githubusercontent.com/26645811/34336958-0b0f01f6-e98e-11e7-929b-85317ed96b00.png)
If there are any further questions, feel free to contact us.
Thank you!

**Comment by haitv282** [comment]
Hi there,

I am so sorry for this. Our colleague has misunderstood your problem.
Regarding this, our technical team has a plan to upgrade the extension to make it compatible with Hybrid 3.0. Please wait for a new version, it may release within 2 or 3 weeks.
Have a nice day.

**Comment by vinaykumar9999** [comment]
Hi
Any updates on this issue.

**Comment by haitv282** [comment]
Hi @vinaykumar9999 
We are waiting for the stable release of Hybrid Auth v3.0 before update our extension.
Please wait for this. Thank you very much.

**Comment by davebra** [comment]
Hello, I want to bump this as Hybridauth 3.0 has been released stable https://github.com/hybridauth/hybridauth/releases/tag/v3.0.0
We are using some crucial extensions based on it and would be awesome if Social Login could support it as well.

**Comment by piotrusin** [comment]
Same as above, can't use it at the moment because of other extensions depending on hybridauth3

**Comment by cmucovic** [comment]
Hello,
We have this error in magento_root/var/report

`{"0":"Endpoint: Error while trying to init Hybrid_Auth: You cannot access this page directly.","1":"<pre>#1 Hybrid_Endpoint->processAuthDone() called at [vendor\/hybridauth\/hybridauth\/hybridauth\/Hybrid\/Endpoint.php:55]\n#2 Hybrid_Endpoint->_construct() called at [vendor\/hybridauth\/hybridauth\/hybridauth\/Hybrid\/Endpoint.php:72]\n#3 Hybrid_Endpoint::process() called at [vendor\/mageplaza\/magento-2-social-login\/Controller\/Social\/Callback.php:56]\n#4 Mageplaza\\SocialLogin\\Controller\\Social
Callback->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#5 Magento\\Framework\\App\\Action
Action->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#6 Mageplaza\\SocialLogin\\Controller\\Social\\Callback
Interceptor->__callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#7 Mageplaza\\SocialLogin\\Controller\\Social\\Callback\\Interceptor->Magento\\Framework\\Interception

{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#8 Mageplaza\\SocialLogin\\Controller\\Social\\Callback
Interceptor->__callPlugins() called at [generated\/code\/Mageplaza\/SocialLogin\/Controller\/Social\/Callback\/Interceptor.php:26]\n#9 Mageplaza\\SocialLogin\\Controller\\Social\\Callback
Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#10 Magento\\Framework\\App
FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#11 Magento\\Framework\\App
FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#12 Magento\\Framework\\App\\FrontController
Interceptor->__callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#13 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception
{closure}
() called at [vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php:94]\n#14 Magento\\Store\\App\\FrontController\\Plugin
RequestPreprocessor->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#15 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception

{closure}() called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:73]\n#16 Magento\\PageCache\\Model\\App\\FrontController
BuiltinPlugin->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#17 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception
{closure}
() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#18 Magento\\Framework\\App\\FrontController
Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#19 Magento\\Framework\\App\\FrontController
Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:136]\n#20 Magento\\Framework\\App
Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:258]\n#21 Magento\\Framework\\App
Bootstrap->run() called at [index.php:39]\n<\/pre>","url":"\/sociallogin\/social\/callback\/?hauth_done=Facebook","script_name":"\/index.php"}`

Is this related problem to what you have described above?
