### ISSUE TITLE
Adblock & Social Login

### ISSUE THREAD

**Issue by mageho** [mageplaza/magento-2-social-login#73]
### Preconditions
1. Magento: 2.2
2. PHP: +7
3. MySQL: +5.6

Adblock block all link and popup for social login.
This is due to use of css class like "social-login", etc.

This is a problem when it touch the header navigation (using popup registration, authentification & password forgotten) which render blank the block generated.

The solution will be to rename these classes to a standard one not blocked by extension Adblock.

Adblock is a solution very popular and a majority of internaut use it.

**Comment by Kenny1994** [comment]
Hi,
Thanks for your suggestion, the reported problem has been approved.
We are going to check the issue and we will notify you when it is fixed.
Please wait for the new update patch, it will be released within 2-3 weeks.
Have a nice day.

**Comment by haitv282** [comment]
Hi,
This problem was solved in our latest version 2.4.2. Please upgrade the extension and check it again.
Thank you very much.

**Comment by invtechservices** [comment]
Hi

I am having this problem with **SocialLogin V2.7.3** and AdBlock+ Version number 3.5.2.
![image](https://user-images.githubusercontent.com/2188562/56908503-1bd0ca80-6aaf-11e9-935c-0e21026974af.png)
When I whitelist the site:
![image](https://user-images.githubusercontent.com/2188562/56908592-4589f180-6aaf-11e9-9200-ae578c557bfb.png)
