### ISSUE TITLE
Login with social account like facebook will crate two same mapping records in database table mageplaza_social_customer

### ISSUE THREAD

**Issue by guaneagler** [mageplaza/magento-2-social-login#74]
I find when user login with facebook, it'll create two same records in database table 'mageplaza_social_customer'
I have check the code and I think it can be avoided by changing little code. 
So I wonder why you let this happen, if you have any reason to do this, please tell me, ths.
`public function createCustomerSocial($data, $store)
    {
        $customer = $this->customerFactory->create();
        $customer->setFirstname($data['firstname'])
            ->setLastname($data['lastname'])
            ->setEmail($data['email'])
            ->setStore($store);

        try {
            $customer->save();

            $this->setAuthorCustomer($data['identifier'], $customer->getId(), $data['type']);

            return $customer;
        } catch (\Exception $e) {
            if ($customer->getId()) {
                $customer->delete();
            }

            throw $e;
        }
    }
`
I think remove the line
` $this->setAuthorCustomer($data['identifier'], $customer->getId(), $data['type']);
`, then it 'll not create two same records.

**Comment by MaxxLuong** [comment]
Hi @guaneagler,
Thank you for your information.We have noted and our team will consider this soon.

**Comment by haitv282** [comment]
Hi @guaneagler,
This problem was solved in our latest version 2.4.2. Please upgrade the extension and check it again.
Thank you very much.
