### ISSUE TITLE
Can you make the hauth_done value in redirect url all lower case

### ISSUE THREAD

**Issue by guaneagler** [mageplaza/magento-2-social-login#75]
For now hauth_done value in redirect url is not all lower case, it's like 'Facebook, Live'. And because of this, the type save in database is same as it,  which make search hard to do.
I know change this will update pre data, you can consider it. ths.

**Comment by MaxxLuong** [comment]
Thank for your information.
We highly appreciate any ideas, suggestions and comments like yours and consider them in our next improvement to make our products better. Thank you very much!
