### ISSUE TITLE
can't work with varnish

### ISSUE THREAD

**Issue by benyang2015** [mageplaza/magento-2-social-login#78]
### Preconditions

1. Magento: 2.2.2
2. PHP: 7.1
3. MySQL: 
4. 
login with facebook ,call back success, but the call back page is xxx.com/customer/login
restart varnish ,customer login with facebook work fine

**Comment by haitv282** [comment]
Hi,
This problem was solved in our latest version 2.4.2. Please upgrade the extension and check it again.
Thank you very much.
