### ISSUE TITLE
could you release a magento-2-thailand-language-pack

### ISSUE THREAD

**Issue by benyang2015** [mageplaza/magento-2-social-login#79]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by haitv282** [comment]
Hi @benyang2015 
Currently, we are seriously lacking personnel, so we cannot build this language package.
We created a [repository](https://github.com/mageplaza/magento-2-thai-language-pack) for this, you can translate by yourself or waiting for contribution from other people.
Thank you very much.
