### ISSUE TITLE
Popup scrolling issue at Mobile Device 

### ISSUE THREAD

**Issue by sunayan-hax** [mageplaza/magento-2-social-login#80]
### Preconditions

1. Magento: 2.1.6
2. PHP: 7 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by haitv282** [comment]
Hi @sunayan-hax 

Could you please explain more detail about this issue? Which device are you using?

**Comment by sunayan-hax** [comment]
**Device:** 
Samsung Galaxy On 5 Pro

**Operating System** : 

Android 7.1.1; SM-G550FY Build/NMF26X

**Browser Version:** 

Google Chrome 64.0.3282.137

**ScreenShot :**  

**Create Account Popup:**
![image](https://user-images.githubusercontent.com/35395217/36885137-2a593e76-1e0b-11e8-80ad-56b59a6ca46c.png)

**Sign In Popup:**
![image](https://user-images.githubusercontent.com/35395217/36885152-4232c09e-1e0b-11e8-8567-9f5deb82231d.png)

**Issue:**
1. In case of **create New Account** Page Till "**Password Field**" are ok. But next field means in case of "**Confirm Password"** & others/submit button i am unable to scroll down browser page. 

2. In case of Sign In page notice that **Social login button** are not visible in single screen. There is also Scrolling issue.

This problem is not only for my store. It also happen Mageplaza Social Login Frontend Demo Version also.

**Comment by imsamthomas** [comment]
Hi,

I have tested on iPhone, did not recreate the issue, see https://imgur.com/gallery/6dDyJ

Our developers/testers will double check this for further information

**Comment by sunayan-hax** [comment]
Hi,
Thanks for your reply.
Just check once it after click on create New account Url. Popup come then.

step 1. Click On **Create an Account** Button without fill any input field. then try scroll popup and check.

if it works then fine. but can you tell me why i am facing this type of issue?

**Comment by MaxxLuong** [comment]
Hi,
You can fix this error by adding the style below the file **..\Mageplaza\SocialLogin\view\frontend\web\css\style.css**
```
.mfp-wrap {
   overflow:scroll;
}
```

**Comment by sunayan-hax** [comment]
Thank you. It works now perfect..
