### ISSUE TITLE
The Google sign-in button is not compliant with the Google sign-in branding guidelines.

### ISSUE THREAD

**Issue by sunayan-hax** [mageplaza/magento-2-social-login#81]
**The Google sign-in button is not compliant with the Google sign-in branding guidelines.**

### Preconditions

1. Magento: 2.1.6
2. PHP: 7

**1. [Screenshot, Which i have got from google verification team]**

![image](https://user-images.githubusercontent.com/35395217/36858044-0e57bbd2-1da0-11e8-891c-35c077c10f55.png)

**Google Signing Branding Guideline Link :** 
[https://developers.google.com/identity/branding-guidelines#top_of_page](url)

**Please check this issue and update google sign in button as per google new branding Guideline.**
**I am Unable to verify for this issue **

**Comment by haitv282** [comment]
Hi @sunayan-hax 
We have just released version 2.5.1 which include the solution for this problem. Please upgrade the extension and test it again.
Thank you very much.
