### ISSUE TITLE
Facebook login requires FB to verify app because of user_about_me

### ISSUE THREAD

**Issue by doctormess** [mageplaza/magento-2-social-login#85]
The Facebook login requests email, user_friends, and user_about_me (your personal description). Because it includes user_about_me, Facebook needs to verify it. Facebook does not need to verify apps if that request public_profile, user_friends, email. So consider removing user_about_me so that we don't need to go through the process of FB verification to get the FB login to work. Consider allowing users to add user_about_me only if needed, via Magento Mageplaza configuration.

See: https://stackoverflow.com/questions/25774586/facebooks-app-permission-message-is-vague-and-unhelpful

### Preconditions

1. Magento: 2.2.3
2. Ubuntu 16.04
3. sociallogin_v2.4.0.1

### Steps to reproduce

1. Install social login plugin in Magento
2. Create app within facebook 
3. Use Facebook App ID and App Secret to configure plugin
4. Try to login to Magento store using Facebook

### Expected result

1. Get access to Magento

### Actual result

1. Warning window, "Submit for Login Review...Some of the permissions below have not been approved for use by Facebook....Submit for review now or learn more...[name of App] will receive: your personal description."

**Comment by doctormess** [comment]
It looks like it is easy to deal with. In magento/app/code/Mageplaza/SocialLogin/Helper/Social.php 

Can remove user_about_me in this line:  'Facebook'  => ["trustForwarded" => false, 'scope' => 'email, user_about_me'],

**Comment by MaxxLuong** [comment]
Hi there,
Thank you for your information. We have noted and our team will consider this soon.

**Comment by sandybrainer** [comment]
I faced this scenario, I guess it is only shown to developers that are associated with a Facebook app. 
Where for the public user logged in works properly.

**Comment by vegangirlthatcodes** [comment]
I removed 'user_about_me' from magento/app/code/Mageplaza/SocialLogin/Helper/Social.php and it works again.
This error is caused because the user_about_me  permission is deprecated since April 4: https://developers.facebook.com/docs/facebook-login/permissions
