### ISSUE TITLE
Customer after signup getting unsubscribe  mail .

### ISSUE THREAD

**Issue by vajor-saurabh** [mageplaza/magento-2-social-login#86]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by vajor-saurabh** [comment]
Hi ,
I have integrated mage plaza social login module , but we have faces some issue , when the customer signup by popup then customer get Unsubscribe e mailer  .

Please suggest me What I do .. ?

**Comment by gixid192** [comment]
Close due to Magento core bug and @vajor-saurabh resolved himself.

**Comment by vajor-saurabh** [comment]
Okay ... :)
