### ISSUE TITLE
We need a help for social login in home page

### ISSUE THREAD

**Issue by sujeetbollywoo** [mageplaza/magento-2-social-login#88]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by sujeetbollywoo** [comment]
Hello Sir,
Can you please explain step or send me screen-shots for we integrate social login in home page as soon as possible ?

**Comment by sujeetbollywoo** [comment]
Anyone there,
Can you please replay ?

**Comment by zebeel** [comment]
Hi there,
Please see this: [Screenshot](http://prntscr.com/iv5woj) | [Video](https://www.screencast.com/t/i2M73UhuNwA0)
If it doesn't work please create a new ticket here: https://mageplaza.freshdesk.com/helpdesk then provide us the SSH information, we will help you config it.
Thank you!

**Comment by gixid192** [comment]
Close due to no response in 7 days
