### ISSUE TITLE
Frontend Error 500

### ISSUE THREAD

**Issue by vishu2707** [mageplaza/magento-2-social-login#89]
I am using Magento 2.2.3 with Redis and Varnish.
I cleared all Cache and static files but still getting error 500 on front end.
Here is the Log description

Uncaught Error: Call to undefined method Mageplaza\\SocialLogin\\Helper\\Data::isEnabled() in /app/code/Mageplaza/SocialLogin/Block/Css.php:62

**Comment by imsamthomas** [comment]
Hi,

Your store is running on old Mageplaza_Core version, you should upgrade to the latest version at https://github.com/mageplaza/module-core/blob/master/README.md#update

**Comment by vishu2707** [comment]
Isuue resolved after removing all extension file and installing through Composer.
