### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Position' not found in /SocialLogin/view/frontend/templates/popup/form/authentication/social.phtml on line 2

### ISSUE THREAD

**Issue by benyang2015** [mageplaza/magento-2-social-login#90]
### Preconditions

1. Magento: 2.2.2
2. PHP: 7.1
3. MySQL: 5.7
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by benyang2015** [comment]
use sociallogin 2.5.1

**Comment by zebeel** [comment]
Please open a ticket here: https://mageplaza.freshdesk.com/helpdesk then provide us some screenshots, FPT, and Backend account. We will help you check this issue.
Thank you!
