### ISSUE TITLE
facebook can't login to website

### ISSUE THREAD

**Issue by benyang2015** [mageplaza/magento-2-social-login#91]
### Preconditions

1. Magento: 2.2.2
2. PHP: 7.1
3. MySQL: 5.7
4. sociallogin version:2.5.1

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

setting all the need
on the frontend ,customer click sigin in with facebook,customer login in the facebook account,call back to the website ,the url is xxx.com/customer/account/login, show you are not login in

**Comment by zebeel** [comment]
Hi there,
Please create a new ticket here: https://mageplaza.freshdesk.com/helpdesk then provide us some screenshots of this issue and the FPT(SSH), backend account of your site. We will check it for you.
Thank you!

**Comment by MaxxLuong** [comment]
Close due to no response in 7 days
