### ISSUE TITLE
Error: Can't Load URL

### ISSUE THREAD

**Issue by rxie-commer** [mageplaza/magento-2-social-login#95]
#

### Preconditions

1. Magento: 2
2. PHP: 7.0.27
3. MySQL: ver 14.14 Distrib 5.7.21-20

### Steps to reproduce

1. install the plugin

### Expected result

1. user can see facebook login page 

### Actual result
My installed the plugin. When I click on the "Sign in With Facebook" button, I always get the following error:
"Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings."

But I do have the domain in my Facebook setting.

I also created a plain HTML page (without Magento). It uses the same Facebook app ID. This page works as expected so I think the problem is in the plugin. If you looked into the URL, the redirect_uri is different with the one generated by the plugin. 

Can you please let me know how to make the plugin work?

Thanks,
Robin Xie

**Comment by MaxxLuong** [comment]
Hi Robin,
You can open a ticket here: [https://mageplaza.freshdesk.com/helpdesk](https://mageplaza.freshdesk.com/helpdesk) then provide us some screenshots, FPT, and Backend information. Our team will help you check this issue.

**Comment by rxie-commer** [comment]
Connected with Beel. Found a problem in my Facebook API setting, the Valid OAuth Redirect URIs field value was not correct. Problem solved. Thanks!

**Comment by MaxxLuong** [comment]
Hi Robin,

I am going to close this ticket now.
If there are any problems arising, please feel free to let us know.
We are always ready to solve them for you!

**Comment by Krishnadcc** [comment]
**Valid OAuth redirect URIs, Google Plus Social login Error .**
After verify email redirect url showing 404 error.

![error](https://user-images.githubusercontent.com/43240222/45488943-9a773280-b780-11e8-9e37-6522bc0542f9.png)
