### ISSUE TITLE
error 500 when trying to use the social login

### ISSUE THREAD

**Issue by eladnm** [mageplaza/magento-2-social-login#96]
i get error 500 when trying to use the social login i installed on my website
[www.globalshop.co.il](www.globalshop.co.il)
not really sure why... cleared cache, reindexd ..

### Preconditions

1. Magento:  2.2.4 dev
2. PHP: 7

### Steps to reproduce

1.  installed the extension copying the files to the app folder
2. set up google and facebook details properly both on their websites and my website

### Actual result
error 500
This page isn’t working
www.globalshop.co.il is currently unable to handle this request.
HTTP ERROR 500

**Comment by MaxxLuong** [comment]
Hi there,
Did you download the library for the Social Login extension?
[https://github.com/mageplaza/magento-2-social-login/tree/library](https://github.com/mageplaza/magento-2-social-login/tree/library)

**Comment by eladnm** [comment]
From here
https://www.mageplaza.com/magento-2-social-login/download/

**Comment by MaxxLuong** [comment]
Now, you can try to download the library, then copy and parse it into the directory [http://prntscr.com/jdjrsh](http://prntscr.com/jdjrsh): 
- ...\dev221\lib\internal\Mageplaza

**Comment by eladnm** [comment]
thanks, but i dont have Mageplaza folder inside my lib/internal folder
only Magento and LinLibertineFont folders

**Comment by MaxxLuong** [comment]
You can open the file ..\app\code\Mageplaza\SocialLogin\Helper\Social.php, then remove user_about_me in the getSocialConfig() function and replace it by "public_profile" [http://prntscr.com/jdlhdw](http://prntscr.com/jdlhdw)

**Comment by eladnm** [comment]
Thanks you very much for all your help!! Very appreciated!

**Comment by MaxxLuong** [comment]
I am going to close this ticket now. If you have any further question/issue, feel free to contact us.
We will be here to assist you.
