### ISSUE TITLE
Helper class not found

### ISSUE THREAD

**Issue by bhupendra2909** [mageplaza/magento-2-social-login#97]
Fatal error: Class 'Mageplaza\Core\Helper\AbstractData' not found in /home/t2jipl/public_html/app/code/Mageplaza/SocialLogin/Helper/Data.php on line 32

**Comment by MaxxLuong** [comment]
Hi there,
This error caused by you are missing the Core module. Please pull or download the late code here: [https://github.com/mageplaza/module-core](https://github.com/mageplaza/module-core)

**Comment by MaxxLuong** [comment]
Close due to no response in 7 days
