### ISSUE TITLE
Facebook authorization doesn't work anymore

### ISSUE THREAD

**Issue by zhartaunik** [mageplaza/magento-2-social-login#98]
The module is using old version of the library "hybridauth/hybridauth": "^2.9.6". As result old version is trying to access deprecated fields. And facebook does not authorize anymore. Facebook is claiming on request following field: "user_about_me".

### Preconditions
Does not matter, though
1. Magento: 2.2.2
2. PHP: 7.1
3. MySQL: 5.6

### Steps to reproduce
1. Configure facebook in backend with your api key to allow authorize from frontend.
2. Try to authorize using facebook

### Expected result
You should be authorized or see facebook window where you may confirm that you allow to provide your personal details

### Actual result
Window with following error:

Invalid Scopes: user_about_me. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

To be sure that the issue relates to 'hybridauth/hybridauth' extension, you may open file in your vendor directory. And remove from following row:
https://github.com/hybridauth/hybridauth/blob/v2.10.0/hybridauth/Hybrid/Providers/Facebook.php#L26
attribute, on which facebook is claiming (in our case it's **user_about_me**).

Possible solutions - ask 'hybridauth/hybridauth' for update 2x version, or update your module to support 3x version.

**Comment by MaxxLuong** [comment]
You can open the file ..\app\code\Mageplaza\SocialLogin\Helper\Social.php, then remove "user_about_me" in the getSocialConfig() function and replace it by "public_profile" [http://prntscr.com/jdlhdw](http://prntscr.com/jdlhdw).

**Comment by MaxxLuong** [comment]
Close due to no response in 7 days
