### ISSUE TITLE
Account automatically logout

### ISSUE THREAD

**Issue by honeygarg** [mageplaza/magento-2-social-login#99]
### Preconditions

1. Magento: 2.2.3
2. PHP: 7.0

### Steps to reproduce
1. User do forget password and then 
sign in with new password 
2 .clicks on my account, 
account logout automatically.

### Expected result
1.  Stay on My account page

### Actual result
1. On click My account, account automatically logout

**Comment by MaxxLuong** [comment]
Hi there,

You can create a ticket here: https://mageplaza.freshdesk.com/helpdesk. Our team will help you check this issue.

**Comment by MaxxLuong** [comment]
Close due to no response in 7 days
